// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dashboard

import (
	"gaap-api/api/base"
	v1 "gaap-api/api/dashboard/v1"
	"gaap-api/internal/model"
)

// summaryToProto converts model.DashboardSummary to protobuf v1.DashboardSummary
func summaryToProto(s *model.DashboardSummary) *v1.DashboardSummary {
	if s == nil {
		return nil
	}
	return &v1.DashboardSummary{
		Assets: &base.Money{
			CurrencyCode: s.CurrencyCode,
			Units:        s.AssetsUnits,
			Nanos:        s.AssetsNanos,
		},
		Liabilities: &base.Money{
			CurrencyCode: s.CurrencyCode,
			Units:        s.LiabilitiesUnits,
			Nanos:        s.LiabilitiesNanos,
		},
		NetWorth: &base.Money{
			CurrencyCode: s.CurrencyCode,
			Units:        s.NetWorthUnits,
			Nanos:        s.NetWorthNanos,
		},
	}
}

// monthlyStatsToProto converts model.MonthlyStats to protobuf v1.MonthlyStats
func monthlyStatsToProto(s *model.MonthlyStats) *v1.MonthlyStats {
	if s == nil {
		return nil
	}
	return &v1.MonthlyStats{
		Income: &base.Money{
			CurrencyCode: s.CurrencyCode,
			Units:        s.IncomeUnits,
			Nanos:        s.IncomeNanos,
		},
		Expense: &base.Money{
			CurrencyCode: s.CurrencyCode,
			Units:        s.ExpenseUnits,
			Nanos:        s.ExpenseNanos,
		},
	}
}

// dailyBalanceToProto converts model.DailyBalance to protobuf v1.DailyBalance
func dailyBalanceToProto(d model.DailyBalance) *v1.DailyBalance {
	result := &v1.DailyBalance{
		Date:     d.Date,
		Balances: make(map[string]*base.Money),
	}
	for accountId, balance := range d.Balances {
		result.Balances[accountId] = &base.Money{
			CurrencyCode: balance.CurrencyCode,
			Units:        balance.Units,
			Nanos:        balance.Nanos,
		}
	}
	return result
}

// dailyBalancesToProtos converts slice of model.DailyBalance to slice of protobuf v1.DailyBalance
func dailyBalancesToProtos(balances []model.DailyBalance) []*v1.DailyBalance {
	result := make([]*v1.DailyBalance, len(balances))
	for i, b := range balances {
		result[i] = dailyBalanceToProto(b)
	}
	return result
}
