// Code generated by genctrl. DO NOT EDIT.
// Source: user/v1/user.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for UserService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfGetProfileReq is the GoFrame-compatible request wrapper for GetProfile
type GfGetProfileReq struct {
	g.Meta `path:"/user/profile" method:"GET" tags:"user" summary:"Get current user profile"`
	*GetUserProfileReq
}

// GfGetProfileRes is the GoFrame-compatible response wrapper for GetProfile
type GfGetProfileRes = GetUserProfileRes


// GfUpdateProfileReq is the GoFrame-compatible request wrapper for UpdateProfile
type GfUpdateProfileReq struct {
	g.Meta `path:"/user/profile" method:"PUT" tags:"user" summary:"Update user profile"`
	*UpdateUserProfileReq
}

// GfUpdateProfileRes is the GoFrame-compatible response wrapper for UpdateProfile
type GfUpdateProfileRes = UpdateUserProfileRes


// GfUpdateThemeReq is the GoFrame-compatible request wrapper for UpdateTheme
type GfUpdateThemeReq struct {
	g.Meta `path:"/user/theme" method:"PUT" tags:"user" summary:"Update user theme preference"`
	*UpdateThemePreferenceReq
}

// GfUpdateThemeRes is the GoFrame-compatible response wrapper for UpdateTheme
type GfUpdateThemeRes = UpdateThemePreferenceRes


