// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user/v1/user.proto

package v1

import (
	base "gaap-api/api/base"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User data structure
type User struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email    string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Nickname string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar   *string                `protobuf:"bytes,4,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	// Plan type: FREE, PRO
	Plan             base.UserLevelType     `protobuf:"varint,5,opt,name=plan,proto3,enum=base.UserLevelType" json:"plan,omitempty" dc:"Plan type: FREE, PRO"`
	TwoFactorEnabled bool                   `protobuf:"varint,6,opt,name=two_factor_enabled,json=twoFactorEnabled,proto3" json:"two_factor_enabled,omitempty"`
	MainCurrency     string                 `protobuf:"bytes,7,opt,name=main_currency,json=mainCurrency,proto3" json:"main_currency,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *User) GetPlan() base.UserLevelType {
	if x != nil {
		return x.Plan
	}
	return base.UserLevelType(0)
}

func (x *User) GetTwoFactorEnabled() bool {
	if x != nil {
		return x.TwoFactorEnabled
	}
	return false
}

func (x *User) GetMainCurrency() string {
	if x != nil {
		return x.MainCurrency
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        *string                `protobuf:"bytes,2,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Plan          base.UserLevelType     `protobuf:"varint,3,opt,name=plan,proto3,enum=base.UserLevelType" json:"plan,omitempty"`
	MainCurrency  *string                `protobuf:"bytes,4,opt,name=main_currency,json=mainCurrency,proto3,oneof" json:"main_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInput) Reset() {
	*x = UserInput{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInput) ProtoMessage() {}

func (x *UserInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInput.ProtoReflect.Descriptor instead.
func (*UserInput) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInput) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInput) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UserInput) GetPlan() base.UserLevelType {
	if x != nil {
		return x.Plan
	}
	return base.UserLevelType(0)
}

func (x *UserInput) GetMainCurrency() string {
	if x != nil && x.MainCurrency != nil {
		return *x.MainCurrency
	}
	return ""
}

type GetUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileReq) Reset() {
	*x = GetUserProfileReq{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileReq) ProtoMessage() {}

func (x *GetUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileReq.ProtoReflect.Descriptor instead.
func (*GetUserProfileReq) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

type GetUserProfileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRes) Reset() {
	*x = GetUserProfileRes{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRes) ProtoMessage() {}

func (x *GetUserProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRes.ProtoReflect.Descriptor instead.
func (*GetUserProfileRes) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserProfileRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type UpdateUserProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *UserInput             `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileReq) Reset() {
	*x = UpdateUserProfileReq{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileReq) ProtoMessage() {}

func (x *UpdateUserProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileReq) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserProfileReq) GetInput() *UserInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UpdateUserProfileRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRes) Reset() {
	*x = UpdateUserProfileRes{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRes) ProtoMessage() {}

func (x *UpdateUserProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRes.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRes) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserProfileRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserProfileRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type UpdateThemePreferenceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         *base.Theme            `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateThemePreferenceReq) Reset() {
	*x = UpdateThemePreferenceReq{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThemePreferenceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThemePreferenceReq) ProtoMessage() {}

func (x *UpdateThemePreferenceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThemePreferenceReq.ProtoReflect.Descriptor instead.
func (*UpdateThemePreferenceReq) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateThemePreferenceReq) GetTheme() *base.Theme {
	if x != nil {
		return x.Theme
	}
	return nil
}

type UpdateThemePreferenceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         *base.Theme            `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateThemePreferenceRes) Reset() {
	*x = UpdateThemePreferenceRes{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateThemePreferenceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateThemePreferenceRes) ProtoMessage() {}

func (x *UpdateThemePreferenceRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateThemePreferenceRes.ProtoReflect.Descriptor instead.
func (*UpdateThemePreferenceRes) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateThemePreferenceRes) GetTheme() *base.Theme {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *UpdateThemePreferenceRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fbase/base.proto\"\xe2\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1b\n" +
	"\x06avatar\x18\x04 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12'\n" +
	"\x04plan\x18\x05 \x01(\x0e2\x13.base.UserLevelTypeR\x04plan\x12,\n" +
	"\x12two_factor_enabled\x18\x06 \x01(\bR\x10twoFactorEnabled\x12#\n" +
	"\rmain_currency\x18\a \x01(\tR\fmainCurrency\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\t\n" +
	"\a_avatar\"\xb4\x01\n" +
	"\tUserInput\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1b\n" +
	"\x06avatar\x18\x02 \x01(\tH\x00R\x06avatar\x88\x01\x01\x12'\n" +
	"\x04plan\x18\x03 \x01(\x0e2\x13.base.UserLevelTypeR\x04plan\x12(\n" +
	"\rmain_currency\x18\x04 \x01(\tH\x01R\fmainCurrency\x88\x01\x01B\t\n" +
	"\a_avatarB\x10\n" +
	"\x0e_main_currency\"\x13\n" +
	"\x11GetUserProfileReq\"_\n" +
	"\x11GetUserProfileRes\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"@\n" +
	"\x14UpdateUserProfileReq\x12(\n" +
	"\x05input\x18\x01 \x01(\v2\x12.user.v1.UserInputR\x05input\"b\n" +
	"\x14UpdateUserProfileRes\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.user.v1.UserR\x04user\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"=\n" +
	"\x18UpdateThemePreferenceReq\x12!\n" +
	"\x05theme\x18\x01 \x01(\v2\v.base.ThemeR\x05theme\"f\n" +
	"\x18UpdateThemePreferenceRes\x12!\n" +
	"\x05theme\x18\x01 \x01(\v2\v.base.ThemeR\x05theme\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base2\xf7\x01\n" +
	"\vUserService\x12D\n" +
	"\n" +
	"GetProfile\x12\x1a.user.v1.GetUserProfileReq\x1a\x1a.user.v1.GetUserProfileRes\x12M\n" +
	"\rUpdateProfile\x12\x1d.user.v1.UpdateUserProfileReq\x1a\x1d.user.v1.UpdateUserProfileRes\x12S\n" +
	"\vUpdateTheme\x12!.user.v1.UpdateThemePreferenceReq\x1a!.user.v1.UpdateThemePreferenceResB\x19Z\x17gaap-api/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_v1_user_proto_goTypes = []any{
	(*User)(nil),                     // 0: user.v1.User
	(*UserInput)(nil),                // 1: user.v1.UserInput
	(*GetUserProfileReq)(nil),        // 2: user.v1.GetUserProfileReq
	(*GetUserProfileRes)(nil),        // 3: user.v1.GetUserProfileRes
	(*UpdateUserProfileReq)(nil),     // 4: user.v1.UpdateUserProfileReq
	(*UpdateUserProfileRes)(nil),     // 5: user.v1.UpdateUserProfileRes
	(*UpdateThemePreferenceReq)(nil), // 6: user.v1.UpdateThemePreferenceReq
	(*UpdateThemePreferenceRes)(nil), // 7: user.v1.UpdateThemePreferenceRes
	(base.UserLevelType)(0),          // 8: base.UserLevelType
	(*timestamppb.Timestamp)(nil),    // 9: google.protobuf.Timestamp
	(*base.BaseResponse)(nil),        // 10: base.BaseResponse
	(*base.Theme)(nil),               // 11: base.Theme
}
var file_user_v1_user_proto_depIdxs = []int32{
	8,  // 0: user.v1.User.plan:type_name -> base.UserLevelType
	9,  // 1: user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: user.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 3: user.v1.UserInput.plan:type_name -> base.UserLevelType
	0,  // 4: user.v1.GetUserProfileRes.user:type_name -> user.v1.User
	10, // 5: user.v1.GetUserProfileRes.base:type_name -> base.BaseResponse
	1,  // 6: user.v1.UpdateUserProfileReq.input:type_name -> user.v1.UserInput
	0,  // 7: user.v1.UpdateUserProfileRes.user:type_name -> user.v1.User
	10, // 8: user.v1.UpdateUserProfileRes.base:type_name -> base.BaseResponse
	11, // 9: user.v1.UpdateThemePreferenceReq.theme:type_name -> base.Theme
	11, // 10: user.v1.UpdateThemePreferenceRes.theme:type_name -> base.Theme
	10, // 11: user.v1.UpdateThemePreferenceRes.base:type_name -> base.BaseResponse
	2,  // 12: user.v1.UserService.GetProfile:input_type -> user.v1.GetUserProfileReq
	4,  // 13: user.v1.UserService.UpdateProfile:input_type -> user.v1.UpdateUserProfileReq
	6,  // 14: user.v1.UserService.UpdateTheme:input_type -> user.v1.UpdateThemePreferenceReq
	3,  // 15: user.v1.UserService.GetProfile:output_type -> user.v1.GetUserProfileRes
	5,  // 16: user.v1.UserService.UpdateProfile:output_type -> user.v1.UpdateUserProfileRes
	7,  // 17: user.v1.UserService.UpdateTheme:output_type -> user.v1.UpdateThemePreferenceRes
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	file_user_v1_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_user_v1_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
