// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package account

import (
	"context"

	v1 "gaap-api/api/account/v1"
	"gaap-api/api/base"
	"gaap-api/internal/middleware"
	"gaap-api/internal/model"
	"gaap-api/internal/model/entity"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// =============================================================================
// Helper functions for PB <-> Entity conversion
// =============================================================================

// requireUserIdFromContext extracts user ID from context, panics if not found
func requireUserIdFromContext(ctx context.Context) uuid.UUID {
	id, ok := ctx.Value(middleware.UserIdKey).(string)
	if !ok || id == "" {
		g.Log().Panicf(ctx, "user id not found in context")
	}
	parsedId, err := uuid.Parse(id)
	if err != nil {
		g.Log().Panicf(ctx, "invalid user id format: %s", id)
	}
	return parsedId
}

// gtimeToDateString safely converts *gtime.Time to date string (YYYY-MM-DD)
func gtimeToDateString(t *gtime.Time) string {
	if t == nil {
		return ""
	}
	return t.Format("Y-m-d")
}

// entityToProto converts entity.Accounts to protobuf v1.Account
func entityToProto(e *entity.Accounts) *v1.Account {
	if e == nil {
		return nil
	}

	account := &v1.Account{
		Id:      e.Id.String(),
		Name:    e.Name,
		Type:    base.AccountType(e.Type),
		IsGroup: e.IsGroup,
		Date:    gtimeToDateString(e.Date),
		Number:  e.Number,
		Remarks: e.Remarks,
		Balance: &base.Money{
			CurrencyCode: e.CurrencyCode,
			Units:        e.BalanceUnits,
			Nanos:        int32(e.BalanceNanos),
		},
	}

	// Optional fields
	if e.ParentId != uuid.Nil {
		parentId := e.ParentId.String()
		account.ParentId = &parentId
	}
	if e.DefaultChildId != uuid.Nil {
		defaultChildId := e.DefaultChildId.String()
		account.DefaultChildId = &defaultChildId
	}
	if e.EquityAccountId != uuid.Nil {
		eqId := e.EquityAccountId.String()
		account.EquityAccountId = &eqId
	}
	if e.CreatedAt != nil {
		account.CreatedAt = timestamppb.New(e.CreatedAt.Time)
	}
	if e.UpdatedAt != nil {
		account.UpdatedAt = timestamppb.New(e.UpdatedAt.Time)
	}

	return account
}

// entitiesToProtos converts a slice of entity.Accounts to protobuf v1.Account slice
func entitiesToProtos(entities []entity.Accounts) []*v1.Account {
	result := make([]*v1.Account, len(entities))
	for i := range entities {
		result[i] = entityToProto(&entities[i])
	}
	return result
}

// protoInputToCreateInput converts protobuf AccountInput to model.AccountCreateInput
func protoInputToCreateInput(ctx context.Context, input *v1.AccountInput) model.AccountCreateInput {
	result := model.AccountCreateInput{
		UserId:  requireUserIdFromContext(ctx),
		Name:    input.GetName(),
		Type:    int(input.GetType()),
		IsGroup: input.GetIsGroup(),
		Date:    input.GetDate(),
		Number:  input.GetNumber(),
		Remarks: input.GetRemarks(),
	}

	// Handle optional parent_id
	if input.GetParentId() != "" {
		if parentId, err := uuid.Parse(input.GetParentId()); err == nil {
			result.ParentId = parentId
		}
	}

	// Handle optional default_child_id
	if input.GetDefaultChildId() != "" {
		if defaultChildId, err := uuid.Parse(input.GetDefaultChildId()); err == nil {
			result.DefaultChildId = defaultChildId
		}
	}

	// Handle balance (Money type)
	if input.GetBalance() != nil {
		result.CurrencyCode = input.GetBalance().GetCurrencyCode()
		result.Units = input.GetBalance().GetUnits()
		result.Nanos = int(input.GetBalance().GetNanos())
	}

	return result
}

// protoInputToUpdateInput converts protobuf AccountInput to model.AccountUpdateInput
func protoInputToUpdateInput(input *v1.AccountInput) model.AccountUpdateInput {
	result := model.AccountUpdateInput{
		Name:    input.GetName(),
		Type:    int(input.GetType()),
		IsGroup: input.GetIsGroup(),
		Date:    input.GetDate(),
		Number:  input.GetNumber(),
		Remarks: input.GetRemarks(),
	}

	// Handle optional parent_id
	if input.GetParentId() != "" {
		if parentId, err := uuid.Parse(input.GetParentId()); err == nil {
			result.ParentId = parentId
		}
	}

	// Handle optional default_child_id
	if input.GetDefaultChildId() != "" {
		if defaultChildId, err := uuid.Parse(input.GetDefaultChildId()); err == nil {
			result.DefaultChildId = defaultChildId
		}
	}

	// Handle balance (Money type)
	if input.GetBalance() != nil {
		result.CurrencyCode = input.GetBalance().GetCurrencyCode()
		units := input.GetBalance().GetUnits()
		nanos := int(input.GetBalance().GetNanos())
		result.BalanceUnits = &units
		result.BalanceNanos = &nanos
	}

	return result
}

// protoQueryToInput converts protobuf AccountQuery to model.AccountQueryInput
func protoQueryToInput(query *v1.AccountQuery) model.AccountQueryInput {
	if query == nil {
		return model.AccountQueryInput{
			Page:  1,
			Limit: 20,
		}
	}

	result := model.AccountQueryInput{
		Page:  int(query.GetPage()),
		Limit: int(query.GetLimit()),
		Type:  int(query.GetType()),
	}

	// Handle optional parent_id
	if query.GetParentId() != "" {
		if parentId, err := uuid.Parse(query.GetParentId()); err == nil {
			result.ParentId = parentId
		}
	}

	// Set defaults
	if result.Page <= 0 {
		result.Page = 1
	}
	if result.Limit <= 0 {
		result.Limit = 20
	}

	return result
}
