// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: transaction/v1/transaction.proto

package v1

import (
	base "gaap-api/api/base"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ISO 8601 Date string
	Date string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty" dc:"ISO 8601 Date string"`
	From string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// Replaced float64 with Money
	Amount *base.Money `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty" dc:"Replaced float64 with Money"`
	Note   string      `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	// Type: INCOME, EXPENSE, TRANSFER
	Type          base.TransactionType   `protobuf:"varint,7,opt,name=type,proto3,enum=base.TransactionType" json:"type,omitempty" Type:"INCOME, EXPENSE, TRANSFER"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Transaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Transaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Transaction) GetAmount() *base.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Transaction) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Transaction) GetType() base.TransactionType {
	if x != nil {
		return x.Type
	}
	return base.TransactionType(0)
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TransactionInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Date  string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	From  string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To    string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// Replaced float64 with Money
	Amount        *base.Money          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty" dc:"Replaced float64 with Money"`
	Note          string               `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	Type          base.TransactionType `protobuf:"varint,6,opt,name=type,proto3,enum=base.TransactionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInput) Reset() {
	*x = TransactionInput{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInput) ProtoMessage() {}

func (x *TransactionInput) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInput.ProtoReflect.Descriptor instead.
func (*TransactionInput) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionInput) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TransactionInput) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransactionInput) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransactionInput) GetAmount() *base.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TransactionInput) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *TransactionInput) GetType() base.TransactionType {
	if x != nil {
		return x.Type
	}
	return base.TransactionType(0)
}

type TransactionQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	StartDate     string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AccountId     string                 `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type          base.TransactionType   `protobuf:"varint,6,opt,name=type,proto3,enum=base.TransactionType" json:"type,omitempty"`
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionQuery) Reset() {
	*x = TransactionQuery{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionQuery) ProtoMessage() {}

func (x *TransactionQuery) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionQuery.ProtoReflect.Descriptor instead.
func (*TransactionQuery) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionQuery) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TransactionQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TransactionQuery) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TransactionQuery) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *TransactionQuery) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TransactionQuery) GetType() base.TransactionType {
	if x != nil {
		return x.Type
	}
	return base.TransactionType(0)
}

func (x *TransactionQuery) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *TransactionQuery) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListTransactionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *TransactionQuery      `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsReq) Reset() {
	*x = ListTransactionsReq{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsReq) ProtoMessage() {}

func (x *ListTransactionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsReq.ProtoReflect.Descriptor instead.
func (*ListTransactionsReq) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ListTransactionsReq) GetQuery() *TransactionQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListTransactionsRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          []*Transaction          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *base.PaginatedResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Base          *base.BaseResponse      `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRes) Reset() {
	*x = ListTransactionsRes{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRes) ProtoMessage() {}

func (x *ListTransactionsRes) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRes.ProtoReflect.Descriptor instead.
func (*ListTransactionsRes) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransactionsRes) GetData() []*Transaction {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTransactionsRes) GetPagination() *base.PaginatedResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTransactionsRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type CreateTransactionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *TransactionInput      `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionReq) Reset() {
	*x = CreateTransactionReq{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionReq) ProtoMessage() {}

func (x *CreateTransactionReq) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionReq.ProtoReflect.Descriptor instead.
func (*CreateTransactionReq) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTransactionReq) GetInput() *TransactionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type CreateTransactionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRes) Reset() {
	*x = CreateTransactionRes{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRes) ProtoMessage() {}

func (x *CreateTransactionRes) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRes.ProtoReflect.Descriptor instead.
func (*CreateTransactionRes) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTransactionRes) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CreateTransactionRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetTransactionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionReq) Reset() {
	*x = GetTransactionReq{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReq) ProtoMessage() {}

func (x *GetTransactionReq) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReq.ProtoReflect.Descriptor instead.
func (*GetTransactionReq) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRes) Reset() {
	*x = GetTransactionRes{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRes) ProtoMessage() {}

func (x *GetTransactionRes) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRes.ProtoReflect.Descriptor instead.
func (*GetTransactionRes) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionRes) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *GetTransactionRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type UpdateTransactionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         *TransactionInput      `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionReq) Reset() {
	*x = UpdateTransactionReq{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionReq) ProtoMessage() {}

func (x *UpdateTransactionReq) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionReq.ProtoReflect.Descriptor instead.
func (*UpdateTransactionReq) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTransactionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTransactionReq) GetInput() *TransactionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UpdateTransactionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRes) Reset() {
	*x = UpdateTransactionRes{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRes) ProtoMessage() {}

func (x *UpdateTransactionRes) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRes.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRes) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTransactionRes) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *UpdateTransactionRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type DeleteTransactionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionReq) Reset() {
	*x = DeleteTransactionReq{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionReq) ProtoMessage() {}

func (x *DeleteTransactionReq) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionReq.ProtoReflect.Descriptor instead.
func (*DeleteTransactionReq) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTransactionReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTransactionRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRes) Reset() {
	*x = DeleteTransactionRes{}
	mi := &file_transaction_v1_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRes) ProtoMessage() {}

func (x *DeleteTransactionRes) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_v1_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRes.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRes) Descriptor() ([]byte, []int) {
	return file_transaction_v1_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTransactionRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_transaction_v1_transaction_proto protoreflect.FileDescriptor

const file_transaction_v1_transaction_proto_rawDesc = "" +
	"\n" +
	" transaction/v1/transaction.proto\x12\x0etransaction.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fbase/base.proto\"\xaf\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\tR\x02to\x12#\n" +
	"\x06amount\x18\x05 \x01(\v2\v.base.MoneyR\x06amount\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\x12)\n" +
	"\x04type\x18\a \x01(\x0e2\x15.base.TransactionTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xae\x01\n" +
	"\x10TransactionInput\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12#\n" +
	"\x06amount\x18\x04 \x01(\v2\v.base.MoneyR\x06amount\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12)\n" +
	"\x04type\x18\x06 \x01(\x0e2\x15.base.TransactionTypeR\x04type\"\xf8\x01\n" +
	"\x10TransactionQuery\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\tR\taccountId\x12)\n" +
	"\x04type\x18\x06 \x01(\x0e2\x15.base.TransactionTypeR\x04type\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\tR\tsortOrder\"M\n" +
	"\x13ListTransactionsReq\x126\n" +
	"\x05query\x18\x01 \x01(\v2 .transaction.v1.TransactionQueryR\x05query\"\xa8\x01\n" +
	"\x13ListTransactionsRes\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.transaction.v1.TransactionR\x04data\x127\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x17.base.PaginatedResponseR\n" +
	"pagination\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"N\n" +
	"\x14CreateTransactionReq\x126\n" +
	"\x05input\x18\x01 \x01(\v2 .transaction.v1.TransactionInputR\x05input\"~\n" +
	"\x14CreateTransactionRes\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.transaction.v1.TransactionR\vtransaction\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"#\n" +
	"\x11GetTransactionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x11GetTransactionRes\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.transaction.v1.TransactionR\vtransaction\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"^\n" +
	"\x14UpdateTransactionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\x05input\x18\x02 \x01(\v2 .transaction.v1.TransactionInputR\x05input\"~\n" +
	"\x14UpdateTransactionRes\x12=\n" +
	"\vtransaction\x18\x01 \x01(\v2\x1b.transaction.v1.TransactionR\vtransaction\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"&\n" +
	"\x14DeleteTransactionReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x14DeleteTransactionRes\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base2\xed\x03\n" +
	"\x12TransactionService\x12\\\n" +
	"\x10ListTransactions\x12#.transaction.v1.ListTransactionsReq\x1a#.transaction.v1.ListTransactionsRes\x12_\n" +
	"\x11CreateTransaction\x12$.transaction.v1.CreateTransactionReq\x1a$.transaction.v1.CreateTransactionRes\x12V\n" +
	"\x0eGetTransaction\x12!.transaction.v1.GetTransactionReq\x1a!.transaction.v1.GetTransactionRes\x12_\n" +
	"\x11UpdateTransaction\x12$.transaction.v1.UpdateTransactionReq\x1a$.transaction.v1.UpdateTransactionRes\x12_\n" +
	"\x11DeleteTransaction\x12$.transaction.v1.DeleteTransactionReq\x1a$.transaction.v1.DeleteTransactionResB Z\x1egaap-api/api/transaction/v1;v1b\x06proto3"

var (
	file_transaction_v1_transaction_proto_rawDescOnce sync.Once
	file_transaction_v1_transaction_proto_rawDescData []byte
)

func file_transaction_v1_transaction_proto_rawDescGZIP() []byte {
	file_transaction_v1_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_v1_transaction_proto_rawDesc), len(file_transaction_v1_transaction_proto_rawDesc)))
	})
	return file_transaction_v1_transaction_proto_rawDescData
}

var file_transaction_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_transaction_v1_transaction_proto_goTypes = []any{
	(*Transaction)(nil),            // 0: transaction.v1.Transaction
	(*TransactionInput)(nil),       // 1: transaction.v1.TransactionInput
	(*TransactionQuery)(nil),       // 2: transaction.v1.TransactionQuery
	(*ListTransactionsReq)(nil),    // 3: transaction.v1.ListTransactionsReq
	(*ListTransactionsRes)(nil),    // 4: transaction.v1.ListTransactionsRes
	(*CreateTransactionReq)(nil),   // 5: transaction.v1.CreateTransactionReq
	(*CreateTransactionRes)(nil),   // 6: transaction.v1.CreateTransactionRes
	(*GetTransactionReq)(nil),      // 7: transaction.v1.GetTransactionReq
	(*GetTransactionRes)(nil),      // 8: transaction.v1.GetTransactionRes
	(*UpdateTransactionReq)(nil),   // 9: transaction.v1.UpdateTransactionReq
	(*UpdateTransactionRes)(nil),   // 10: transaction.v1.UpdateTransactionRes
	(*DeleteTransactionReq)(nil),   // 11: transaction.v1.DeleteTransactionReq
	(*DeleteTransactionRes)(nil),   // 12: transaction.v1.DeleteTransactionRes
	(*base.Money)(nil),             // 13: base.Money
	(base.TransactionType)(0),      // 14: base.TransactionType
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
	(*base.PaginatedResponse)(nil), // 16: base.PaginatedResponse
	(*base.BaseResponse)(nil),      // 17: base.BaseResponse
}
var file_transaction_v1_transaction_proto_depIdxs = []int32{
	13, // 0: transaction.v1.Transaction.amount:type_name -> base.Money
	14, // 1: transaction.v1.Transaction.type:type_name -> base.TransactionType
	15, // 2: transaction.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: transaction.v1.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	13, // 4: transaction.v1.TransactionInput.amount:type_name -> base.Money
	14, // 5: transaction.v1.TransactionInput.type:type_name -> base.TransactionType
	14, // 6: transaction.v1.TransactionQuery.type:type_name -> base.TransactionType
	2,  // 7: transaction.v1.ListTransactionsReq.query:type_name -> transaction.v1.TransactionQuery
	0,  // 8: transaction.v1.ListTransactionsRes.data:type_name -> transaction.v1.Transaction
	16, // 9: transaction.v1.ListTransactionsRes.pagination:type_name -> base.PaginatedResponse
	17, // 10: transaction.v1.ListTransactionsRes.base:type_name -> base.BaseResponse
	1,  // 11: transaction.v1.CreateTransactionReq.input:type_name -> transaction.v1.TransactionInput
	0,  // 12: transaction.v1.CreateTransactionRes.transaction:type_name -> transaction.v1.Transaction
	17, // 13: transaction.v1.CreateTransactionRes.base:type_name -> base.BaseResponse
	0,  // 14: transaction.v1.GetTransactionRes.transaction:type_name -> transaction.v1.Transaction
	17, // 15: transaction.v1.GetTransactionRes.base:type_name -> base.BaseResponse
	1,  // 16: transaction.v1.UpdateTransactionReq.input:type_name -> transaction.v1.TransactionInput
	0,  // 17: transaction.v1.UpdateTransactionRes.transaction:type_name -> transaction.v1.Transaction
	17, // 18: transaction.v1.UpdateTransactionRes.base:type_name -> base.BaseResponse
	17, // 19: transaction.v1.DeleteTransactionRes.base:type_name -> base.BaseResponse
	3,  // 20: transaction.v1.TransactionService.ListTransactions:input_type -> transaction.v1.ListTransactionsReq
	5,  // 21: transaction.v1.TransactionService.CreateTransaction:input_type -> transaction.v1.CreateTransactionReq
	7,  // 22: transaction.v1.TransactionService.GetTransaction:input_type -> transaction.v1.GetTransactionReq
	9,  // 23: transaction.v1.TransactionService.UpdateTransaction:input_type -> transaction.v1.UpdateTransactionReq
	11, // 24: transaction.v1.TransactionService.DeleteTransaction:input_type -> transaction.v1.DeleteTransactionReq
	4,  // 25: transaction.v1.TransactionService.ListTransactions:output_type -> transaction.v1.ListTransactionsRes
	6,  // 26: transaction.v1.TransactionService.CreateTransaction:output_type -> transaction.v1.CreateTransactionRes
	8,  // 27: transaction.v1.TransactionService.GetTransaction:output_type -> transaction.v1.GetTransactionRes
	10, // 28: transaction.v1.TransactionService.UpdateTransaction:output_type -> transaction.v1.UpdateTransactionRes
	12, // 29: transaction.v1.TransactionService.DeleteTransaction:output_type -> transaction.v1.DeleteTransactionRes
	25, // [25:30] is the sub-list for method output_type
	20, // [20:25] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_transaction_v1_transaction_proto_init() }
func file_transaction_v1_transaction_proto_init() {
	if File_transaction_v1_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_v1_transaction_proto_rawDesc), len(file_transaction_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_v1_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_v1_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_v1_transaction_proto_msgTypes,
	}.Build()
	File_transaction_v1_transaction_proto = out.File
	file_transaction_v1_transaction_proto_goTypes = nil
	file_transaction_v1_transaction_proto_depIdxs = nil
}
