// Code generated by genctrl. DO NOT EDIT.
// Source: transaction/v1/transaction.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for TransactionService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfListTransactionsReq is the GoFrame-compatible request wrapper for ListTransactions
type GfListTransactionsReq struct {
	g.Meta `path:"/v1/transaction/list-transactions" method:"POST" tags:"transaction" summary:"List transactions"`
	ListTransactionsReq
}

// GfListTransactionsRes is the GoFrame-compatible response wrapper for ListTransactions
type GfListTransactionsRes = ListTransactionsRes


// GfCreateTransactionReq is the GoFrame-compatible request wrapper for CreateTransaction
type GfCreateTransactionReq struct {
	g.Meta `path:"/v1/transaction/create-transaction" method:"POST" tags:"transaction" summary:"Create a new transaction"`
	CreateTransactionReq
}

// GfCreateTransactionRes is the GoFrame-compatible response wrapper for CreateTransaction
type GfCreateTransactionRes = CreateTransactionRes


// GfGetTransactionReq is the GoFrame-compatible request wrapper for GetTransaction
type GfGetTransactionReq struct {
	g.Meta `path:"/v1/transaction/get-transaction" method:"POST" tags:"transaction" summary:"Get transaction details"`
	GetTransactionReq
}

// GfGetTransactionRes is the GoFrame-compatible response wrapper for GetTransaction
type GfGetTransactionRes = GetTransactionRes


// GfUpdateTransactionReq is the GoFrame-compatible request wrapper for UpdateTransaction
type GfUpdateTransactionReq struct {
	g.Meta `path:"/v1/transaction/update-transaction" method:"POST" tags:"transaction" summary:"Update transaction"`
	UpdateTransactionReq
}

// GfUpdateTransactionRes is the GoFrame-compatible response wrapper for UpdateTransaction
type GfUpdateTransactionRes = UpdateTransactionRes


// GfDeleteTransactionReq is the GoFrame-compatible request wrapper for DeleteTransaction
type GfDeleteTransactionReq struct {
	g.Meta `path:"/v1/transaction/delete-transaction" method:"POST" tags:"transaction" summary:"Delete transaction"`
	DeleteTransactionReq
}

// GfDeleteTransactionRes is the GoFrame-compatible response wrapper for DeleteTransaction
type GfDeleteTransactionRes = DeleteTransactionRes


