// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"gaap-api/api/base"
	userV1 "gaap-api/api/user/v1"
	"gaap-api/internal/model"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// userProfileToProto converts model.UserProfile to protobuf userV1.User
func userProfileToProto(p *model.UserProfile) *userV1.User {
	if p == nil {
		return nil
	}
	user := &userV1.User{
		Email:            p.Email,
		Nickname:         p.Nickname,
		Plan:             base.UserLevelType(p.Plan),
		TwoFactorEnabled: p.TwoFactorEnabled,
		MainCurrency:     p.MainCurrency,
	}

	if p.Avatar != "" {
		user.Avatar = &p.Avatar
	}

	return user
}

// themeToProto converts model.Theme to protobuf base.Theme
func themeToProto(t *model.Theme) *base.Theme {
	if t == nil {
		return nil
	}
	return &base.Theme{
		Id:     t.Id.String(),
		Name:   t.Name,
		IsDark: t.IsDark,
		Colors: &base.ThemeColors{
			Primary: t.Colors.Primary,
			Bg:      t.Colors.Bg,
			Card:    t.Colors.Card,
			Text:    t.Colors.Text,
			Muted:   t.Colors.Muted,
			Border:  t.Colors.Border,
		},
	}
}

// _ is used to satisfy unused import for timestamppb
var _ = timestamppb.Now
