// Code generated by genctrl. DO NOT EDIT.
// Source: hello/v1/hello.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for HelloService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfHelloReq is the GoFrame-compatible request wrapper for Hello
type GfHelloReq struct {
	g.Meta `path:"/hello/hello" method:"POST" tags:"hello" summary:"You first hello api"`
	*HelloReq
}

// GfHelloRes is the GoFrame-compatible response wrapper for Hello
type GfHelloRes = HelloRes


