// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: base/base.proto

package base

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Share enum
// Account Type
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0 // Default
	AccountType_ACCOUNT_TYPE_ASSET       AccountType = 1
	AccountType_ACCOUNT_TYPE_LIABILITY   AccountType = 2
	AccountType_ACCOUNT_TYPE_INCOME      AccountType = 3
	AccountType_ACCOUNT_TYPE_EXPENSE     AccountType = 4
	AccountType_ACCOUNT_TYPE_EQUITY      AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_ASSET",
		2: "ACCOUNT_TYPE_LIABILITY",
		3: "ACCOUNT_TYPE_INCOME",
		4: "ACCOUNT_TYPE_EXPENSE",
		5: "ACCOUNT_TYPE_EQUITY",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_ASSET":       1,
		"ACCOUNT_TYPE_LIABILITY":   2,
		"ACCOUNT_TYPE_INCOME":      3,
		"ACCOUNT_TYPE_EXPENSE":     4,
		"ACCOUNT_TYPE_EQUITY":      5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_base_base_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_base_base_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{0}
}

// Transaction Type
type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED     TransactionType = 0 // Default
	TransactionType_TRANSACTION_TYPE_INCOME          TransactionType = 1
	TransactionType_TRANSACTION_TYPE_EXPENSE         TransactionType = 2
	TransactionType_TRANSACTION_TYPE_TRANSFER        TransactionType = 3
	TransactionType_TRANSACTION_TYPE_OPENING_BALANCE TransactionType = 4
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_INCOME",
		2: "TRANSACTION_TYPE_EXPENSE",
		3: "TRANSACTION_TYPE_TRANSFER",
		4: "TRANSACTION_TYPE_OPENING_BALANCE",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED":     0,
		"TRANSACTION_TYPE_INCOME":          1,
		"TRANSACTION_TYPE_EXPENSE":         2,
		"TRANSACTION_TYPE_TRANSFER":        3,
		"TRANSACTION_TYPE_OPENING_BALANCE": 4,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_base_base_proto_enumTypes[1].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_base_base_proto_enumTypes[1]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{1}
}

// User Level Type
type UserLevelType int32

const (
	UserLevelType_USER_LEVEL_TYPE_UNSPECIFIED UserLevelType = 0 // Default
	UserLevelType_USER_LEVEL_TYPE_FREE        UserLevelType = 1
	UserLevelType_USER_LEVEL_TYPE_PRO         UserLevelType = 2
)

// Enum value maps for UserLevelType.
var (
	UserLevelType_name = map[int32]string{
		0: "USER_LEVEL_TYPE_UNSPECIFIED",
		1: "USER_LEVEL_TYPE_FREE",
		2: "USER_LEVEL_TYPE_PRO",
	}
	UserLevelType_value = map[string]int32{
		"USER_LEVEL_TYPE_UNSPECIFIED": 0,
		"USER_LEVEL_TYPE_FREE":        1,
		"USER_LEVEL_TYPE_PRO":         2,
	}
)

func (x UserLevelType) Enum() *UserLevelType {
	p := new(UserLevelType)
	*p = x
	return p
}

func (x UserLevelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserLevelType) Descriptor() protoreflect.EnumDescriptor {
	return file_base_base_proto_enumTypes[2].Descriptor()
}

func (UserLevelType) Type() protoreflect.EnumType {
	return &file_base_base_proto_enumTypes[2]
}

func (x UserLevelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserLevelType.Descriptor instead.
func (UserLevelType) EnumDescriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{2}
}

// Base response included in most API responses
type BaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResponse) Reset() {
	*x = BaseResponse{}
	mi := &file_base_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResponse) ProtoMessage() {}

func (x *BaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResponse.ProtoReflect.Descriptor instead.
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Pagination metadata
type PaginatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedResponse) Reset() {
	*x = PaginatedResponse{}
	mi := &file_base_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedResponse) ProtoMessage() {}

func (x *PaginatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedResponse.ProtoReflect.Descriptor instead.
func (*PaginatedResponse) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{1}
}

func (x *PaginatedResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginatedResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginatedResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginatedResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// User theme preference
type Theme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDark        bool                   `protobuf:"varint,3,opt,name=is_dark,json=isDark,proto3" json:"is_dark,omitempty"`
	Colors        *ThemeColors           `protobuf:"bytes,4,opt,name=colors,proto3" json:"colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Theme) Reset() {
	*x = Theme{}
	mi := &file_base_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Theme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Theme) ProtoMessage() {}

func (x *Theme) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Theme.ProtoReflect.Descriptor instead.
func (*Theme) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{2}
}

func (x *Theme) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Theme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Theme) GetIsDark() bool {
	if x != nil {
		return x.IsDark
	}
	return false
}

func (x *Theme) GetColors() *ThemeColors {
	if x != nil {
		return x.Colors
	}
	return nil
}

// Specific colors for the theme
type ThemeColors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Primary       string                 `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Bg            string                 `protobuf:"bytes,2,opt,name=bg,proto3" json:"bg,omitempty"`
	Card          string                 `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Muted         string                 `protobuf:"bytes,5,opt,name=muted,proto3" json:"muted,omitempty"`
	Border        string                 `protobuf:"bytes,6,opt,name=border,proto3" json:"border,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemeColors) Reset() {
	*x = ThemeColors{}
	mi := &file_base_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeColors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeColors) ProtoMessage() {}

func (x *ThemeColors) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeColors.ProtoReflect.Descriptor instead.
func (*ThemeColors) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{3}
}

func (x *ThemeColors) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *ThemeColors) GetBg() string {
	if x != nil {
		return x.Bg
	}
	return ""
}

func (x *ThemeColors) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *ThemeColors) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ThemeColors) GetMuted() string {
	if x != nil {
		return x.Muted
	}
	return ""
}

func (x *ThemeColors) GetBorder() string {
	if x != nil {
		return x.Border
	}
	return ""
}

// UI configuration for account types
type AccountTypeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	Bg            string                 `protobuf:"bytes,3,opt,name=bg,proto3" json:"bg,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountTypeConfig) Reset() {
	*x = AccountTypeConfig{}
	mi := &file_base_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTypeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTypeConfig) ProtoMessage() {}

func (x *AccountTypeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTypeConfig.ProtoReflect.Descriptor instead.
func (*AccountTypeConfig) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{4}
}

func (x *AccountTypeConfig) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AccountTypeConfig) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *AccountTypeConfig) GetBg() string {
	if x != nil {
		return x.Bg
	}
	return ""
}

func (x *AccountTypeConfig) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

// Share messages
type Money struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO 4217 Currency Code, such as "CNY", "USD", "JPY"
	// If it's a stock or custom asset, use "AAPL", "BTC"
	CurrencyCode string `protobuf:"bytes,1,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty" dc:"ISO 4217 Currency Code, such as 'CNY', 'USD', 'JPY'If it's a stock or custom asset, use 'AAPL', 'BTC'"`
	// Integer part. For example, 100.50 yuan, store 100
	Units int64 `protobuf:"varint,2,opt,name=units,proto3" json:"units,omitempty" dc:"Integer part. For example, 100.50 yuan, store 100"`
	// Decimal part, in nanos (10^-9). For example, 0.50 yuan, store 500,000,000
	// Range must be between -999,999,999 and +999,999,999
	Nanos         int32 `protobuf:"varint,3,opt,name=nanos,proto3" json:"nanos,omitempty" dc:"Decimal part, in nanos (10^-9). For example, 0.50 yuan, store 500,000,000Range must be between -999,999,999 and +999,999,999"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_base_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_base_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_base_base_proto_rawDescGZIP(), []int{5}
}

func (x *Money) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Money) GetUnits() int64 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Money) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

var File_base_base_proto protoreflect.FileDescriptor

const file_base_base_proto_rawDesc = "" +
	"\n" +
	"\x0fbase/base.proto\x12\x04base\"(\n" +
	"\fBaseResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"t\n" +
	"\x11PaginatedResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"o\n" +
	"\x05Theme\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\ais_dark\x18\x03 \x01(\bR\x06isDark\x12)\n" +
	"\x06colors\x18\x04 \x01(\v2\x11.base.ThemeColorsR\x06colors\"\x8d\x01\n" +
	"\vThemeColors\x12\x18\n" +
	"\aprimary\x18\x01 \x01(\tR\aprimary\x12\x0e\n" +
	"\x02bg\x18\x02 \x01(\tR\x02bg\x12\x12\n" +
	"\x04card\x18\x03 \x01(\tR\x04card\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05muted\x18\x05 \x01(\tR\x05muted\x12\x16\n" +
	"\x06border\x18\x06 \x01(\tR\x06border\"c\n" +
	"\x11AccountTypeConfig\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x0e\n" +
	"\x02bg\x18\x03 \x01(\tR\x02bg\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\"X\n" +
	"\x05Money\x12#\n" +
	"\rcurrency_code\x18\x01 \x01(\tR\fcurrencyCode\x12\x14\n" +
	"\x05units\x18\x02 \x01(\x03R\x05units\x12\x14\n" +
	"\x05nanos\x18\x03 \x01(\x05R\x05nanos*\xab\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACCOUNT_TYPE_ASSET\x10\x01\x12\x1a\n" +
	"\x16ACCOUNT_TYPE_LIABILITY\x10\x02\x12\x17\n" +
	"\x13ACCOUNT_TYPE_INCOME\x10\x03\x12\x18\n" +
	"\x14ACCOUNT_TYPE_EXPENSE\x10\x04\x12\x17\n" +
	"\x13ACCOUNT_TYPE_EQUITY\x10\x05*\xb3\x01\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRANSACTION_TYPE_INCOME\x10\x01\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_EXPENSE\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_TYPE_TRANSFER\x10\x03\x12$\n" +
	" TRANSACTION_TYPE_OPENING_BALANCE\x10\x04*c\n" +
	"\rUserLevelType\x12\x1f\n" +
	"\x1bUSER_LEVEL_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14USER_LEVEL_TYPE_FREE\x10\x01\x12\x17\n" +
	"\x13USER_LEVEL_TYPE_PRO\x10\x02B\x18Z\x16gaap-api/api/base;baseb\x06proto3"

var (
	file_base_base_proto_rawDescOnce sync.Once
	file_base_base_proto_rawDescData []byte
)

func file_base_base_proto_rawDescGZIP() []byte {
	file_base_base_proto_rawDescOnce.Do(func() {
		file_base_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_base_proto_rawDesc), len(file_base_base_proto_rawDesc)))
	})
	return file_base_base_proto_rawDescData
}

var file_base_base_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_base_base_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_base_base_proto_goTypes = []any{
	(AccountType)(0),          // 0: base.AccountType
	(TransactionType)(0),      // 1: base.TransactionType
	(UserLevelType)(0),        // 2: base.UserLevelType
	(*BaseResponse)(nil),      // 3: base.BaseResponse
	(*PaginatedResponse)(nil), // 4: base.PaginatedResponse
	(*Theme)(nil),             // 5: base.Theme
	(*ThemeColors)(nil),       // 6: base.ThemeColors
	(*AccountTypeConfig)(nil), // 7: base.AccountTypeConfig
	(*Money)(nil),             // 8: base.Money
}
var file_base_base_proto_depIdxs = []int32{
	6, // 0: base.Theme.colors:type_name -> base.ThemeColors
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_base_base_proto_init() }
func file_base_base_proto_init() {
	if File_base_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_base_proto_rawDesc), len(file_base_base_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_base_proto_goTypes,
		DependencyIndexes: file_base_base_proto_depIdxs,
		EnumInfos:         file_base_base_proto_enumTypes,
		MessageInfos:      file_base_base_proto_msgTypes,
	}.Build()
	File_base_base_proto = out.File
	file_base_base_proto_goTypes = nil
	file_base_base_proto_depIdxs = nil
}
