// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	v1 "gaap-api/api/auth/v1"
	"gaap-api/api/base"
	userV1 "gaap-api/api/user/v1"
	"gaap-api/internal/model"
	"gaap-api/internal/model/entity"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// =============================================================================
// Helper functions for PB <-> Model conversion
// =============================================================================

// userEntityToProto converts entity.Users to protobuf userV1.User
func userEntityToProto(e *entity.Users) *userV1.User {
	if e == nil {
		return nil
	}

	user := &userV1.User{
		Id:               e.Id.String(),
		Email:            e.Email,
		Nickname:         e.Nickname,
		Avatar:           &e.Avatar,
		Plan:             base.UserLevelType(e.Plan),
		MainCurrency:     e.MainCurrency,
		TwoFactorEnabled: e.TwoFactorEnabled,
	}

	if e.CreatedAt != nil {
		user.CreatedAt = timestamppb.New(e.CreatedAt.Time)
	}
	if e.UpdatedAt != nil {
		user.UpdatedAt = timestamppb.New(e.UpdatedAt.Time)
	}

	return user
}

// authResponseToProto converts model.AuthResponse to protobuf v1.AuthResponse
func authResponseToProto(resp *model.AuthResponse) *v1.AuthResponse {
	if resp == nil {
		return nil
	}
	return &v1.AuthResponse{
		AccessToken:  resp.AccessToken,
		RefreshToken: resp.RefreshToken,
		User:         userEntityToProto(resp.User),
		SessionKey:   resp.SessionKey,
	}
}

// twoFactorSecretToProto converts model.TwoFactorSecret to protobuf v1.TwoFactorSecret
func twoFactorSecretToProto(secret *model.TwoFactorSecret) *v1.TwoFactorSecret {
	if secret == nil {
		return nil
	}
	return &v1.TwoFactorSecret{
		Secret: secret.Secret,
		Url:    secret.Url,
	}
}
