// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package task

import (
	"gaap-api/api/base"
	v1 "gaap-api/api/task/v1"
	"gaap-api/internal/model"

	"google.golang.org/protobuf/types/known/structpb"
)

// taskToProto converts model.Task to protobuf v1.Task
func taskToProto(t *model.Task) *v1.Task {
	if t == nil {
		return nil
	}

	task := &v1.Task{
		Id:             t.Id.String(),
		Type:           v1.TaskType(t.Type),
		Status:         v1.TaskStatus(t.Status),
		Progress:       int32(t.Progress),
		TotalItems:     int32(t.TotalItems),
		ProcessedItems: int32(t.ProcessedItems),
	}

	// Convert payload and result to structpb.Struct if possible
	if t.Payload != nil {
		if payloadStruct, err := structpb.NewStruct(nil); err == nil {
			task.Payload = payloadStruct
		}
	}
	if t.Result != nil {
		if resultStruct, err := structpb.NewStruct(nil); err == nil {
			task.Result = resultStruct
		}
	}

	return task
}

// tasksToProtos converts slice of model.Task to slice of protobuf v1.Task
func tasksToProtos(tasks []model.Task) []*v1.Task {
	result := make([]*v1.Task, len(tasks))
	for i := range tasks {
		result[i] = taskToProto(&tasks[i])
	}
	return result
}

// _ is used to satisfy unused import for base
var _ = base.BaseResponse{}
