// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: account/v1/account.proto

package v1

import (
	base "gaap-api/api/base"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId *string                `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name     string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type     base.AccountType       `protobuf:"varint,4,opt,name=type,proto3,enum=base.AccountType" json:"type,omitempty"`
	IsGroup  bool                   `protobuf:"varint,5,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	// Replaced float64 with Money
	Balance        *base.Money `protobuf:"bytes,6,opt,name=balance,proto3" json:"balance,omitempty" dc:"Replaced float64 with Money"`
	DefaultChildId *string     `protobuf:"bytes,7,opt,name=default_child_id,json=defaultChildId,proto3,oneof" json:"default_child_id,omitempty"`
	// ISO 8601 Date string
	Date             string                 `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty" dc:"ISO 8601 Date string"`
	Number           string                 `protobuf:"bytes,9,opt,name=number,proto3" json:"number,omitempty"`
	Remarks          string                 `protobuf:"bytes,10,opt,name=remarks,proto3" json:"remarks,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OpeningVoucherId string                 `protobuf:"bytes,13,opt,name=opening_voucher_id,json=openingVoucherId,proto3" json:"opening_voucher_id,omitempty"`
	EquityAccountId  *string                `protobuf:"bytes,14,opt,name=equity_account_id,json=equityAccountId,proto3,oneof" json:"equity_account_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetType() base.AccountType {
	if x != nil {
		return x.Type
	}
	return base.AccountType(0)
}

func (x *Account) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *Account) GetBalance() *base.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *Account) GetDefaultChildId() string {
	if x != nil && x.DefaultChildId != nil {
		return *x.DefaultChildId
	}
	return ""
}

func (x *Account) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Account) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Account) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Account) GetOpeningVoucherId() string {
	if x != nil {
		return x.OpeningVoucherId
	}
	return ""
}

func (x *Account) GetEquityAccountId() string {
	if x != nil && x.EquityAccountId != nil {
		return *x.EquityAccountId
	}
	return ""
}

type AccountInput struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ParentId *string                `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type     base.AccountType       `protobuf:"varint,3,opt,name=type,proto3,enum=base.AccountType" json:"type,omitempty"`
	IsGroup  bool                   `protobuf:"varint,4,opt,name=is_group,json=isGroup,proto3" json:"is_group,omitempty"`
	// Replaced float64 with Money
	Balance        *base.Money `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty" dc:"Replaced float64 with Money"`
	DefaultChildId *string     `protobuf:"bytes,6,opt,name=default_child_id,json=defaultChildId,proto3,oneof" json:"default_child_id,omitempty"`
	Date           string      `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Number         *string     `protobuf:"bytes,8,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Remarks        *string     `protobuf:"bytes,9,opt,name=remarks,proto3,oneof" json:"remarks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountInput) Reset() {
	*x = AccountInput{}
	mi := &file_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInput) ProtoMessage() {}

func (x *AccountInput) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInput.ProtoReflect.Descriptor instead.
func (*AccountInput) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *AccountInput) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *AccountInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccountInput) GetType() base.AccountType {
	if x != nil {
		return x.Type
	}
	return base.AccountType(0)
}

func (x *AccountInput) GetIsGroup() bool {
	if x != nil {
		return x.IsGroup
	}
	return false
}

func (x *AccountInput) GetBalance() *base.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *AccountInput) GetDefaultChildId() string {
	if x != nil && x.DefaultChildId != nil {
		return *x.DefaultChildId
	}
	return ""
}

func (x *AccountInput) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AccountInput) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

func (x *AccountInput) GetRemarks() string {
	if x != nil && x.Remarks != nil {
		return *x.Remarks
	}
	return ""
}

type AccountQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Type          base.AccountType       `protobuf:"varint,3,opt,name=type,proto3,enum=base.AccountType" json:"type,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountQuery) Reset() {
	*x = AccountQuery{}
	mi := &file_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountQuery) ProtoMessage() {}

func (x *AccountQuery) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountQuery.ProtoReflect.Descriptor instead.
func (*AccountQuery) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *AccountQuery) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AccountQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AccountQuery) GetType() base.AccountType {
	if x != nil {
		return x.Type
	}
	return base.AccountType(0)
}

func (x *AccountQuery) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListAccountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *AccountQuery          `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsReq) Reset() {
	*x = ListAccountsReq{}
	mi := &file_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsReq) ProtoMessage() {}

func (x *ListAccountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsReq.ProtoReflect.Descriptor instead.
func (*ListAccountsReq) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccountsReq) GetQuery() *AccountQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListAccountsRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          []*Account              `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *base.PaginatedResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Base          *base.BaseResponse      `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRes) Reset() {
	*x = ListAccountsRes{}
	mi := &file_account_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRes) ProtoMessage() {}

func (x *ListAccountsRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRes.ProtoReflect.Descriptor instead.
func (*ListAccountsRes) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountsRes) GetData() []*Account {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListAccountsRes) GetPagination() *base.PaginatedResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAccountsRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type CreateAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         *AccountInput          `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountReq) Reset() {
	*x = CreateAccountReq{}
	mi := &file_account_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReq) ProtoMessage() {}

func (x *CreateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReq.ProtoReflect.Descriptor instead.
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountReq) GetInput() *AccountInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type CreateAccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRes) Reset() {
	*x = CreateAccountRes{}
	mi := &file_account_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRes) ProtoMessage() {}

func (x *CreateAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRes.ProtoReflect.Descriptor instead.
func (*CreateAccountRes) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountRes) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CreateAccountRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountReq) Reset() {
	*x = GetAccountReq{}
	mi := &file_account_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountReq) ProtoMessage() {}

func (x *GetAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountReq.ProtoReflect.Descriptor instead.
func (*GetAccountReq) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRes) Reset() {
	*x = GetAccountRes{}
	mi := &file_account_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRes) ProtoMessage() {}

func (x *GetAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRes.ProtoReflect.Descriptor instead.
func (*GetAccountRes) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountRes) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type UpdateAccountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Input         *AccountInput          `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountReq) Reset() {
	*x = UpdateAccountReq{}
	mi := &file_account_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountReq) ProtoMessage() {}

func (x *UpdateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountReq.ProtoReflect.Descriptor instead.
func (*UpdateAccountReq) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAccountReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccountReq) GetInput() *AccountInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type UpdateAccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRes) Reset() {
	*x = UpdateAccountRes{}
	mi := &file_account_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRes) ProtoMessage() {}

func (x *UpdateAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRes.ProtoReflect.Descriptor instead.
func (*UpdateAccountRes) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateAccountRes) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *UpdateAccountRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type DeleteAccountReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// map<currency, targetAccountId>
	MigrationTargets map[string]string `protobuf:"bytes,2,rep,name=migration_targets,json=migrationTargets,proto3" json:"migration_targets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" dc:"map<currency, targetAccountId>"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteAccountReq) Reset() {
	*x = DeleteAccountReq{}
	mi := &file_account_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountReq) ProtoMessage() {}

func (x *DeleteAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountReq.ProtoReflect.Descriptor instead.
func (*DeleteAccountReq) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteAccountReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAccountReq) GetMigrationTargets() map[string]string {
	if x != nil {
		return x.MigrationTargets
	}
	return nil
}

type DeleteAccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRes) Reset() {
	*x = DeleteAccountRes{}
	mi := &file_account_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRes) ProtoMessage() {}

func (x *DeleteAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRes.ProtoReflect.Descriptor instead.
func (*DeleteAccountRes) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteAccountRes) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *DeleteAccountRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetAccountTransactionCountReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTransactionCountReq) Reset() {
	*x = GetAccountTransactionCountReq{}
	mi := &file_account_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTransactionCountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransactionCountReq) ProtoMessage() {}

func (x *GetAccountTransactionCountReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransactionCountReq.ProtoReflect.Descriptor instead.
func (*GetAccountTransactionCountReq) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *GetAccountTransactionCountReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAccountTransactionCountRes struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Count              int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	CountWithoutEquity int32                  `protobuf:"varint,2,opt,name=count_without_equity,json=countWithoutEquity,proto3" json:"count_without_equity,omitempty"`
	Base               *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAccountTransactionCountRes) Reset() {
	*x = GetAccountTransactionCountRes{}
	mi := &file_account_v1_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTransactionCountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTransactionCountRes) ProtoMessage() {}

func (x *GetAccountTransactionCountRes) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTransactionCountRes.ProtoReflect.Descriptor instead.
func (*GetAccountTransactionCountRes) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{14}
}

func (x *GetAccountTransactionCountRes) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetAccountTransactionCountRes) GetCountWithoutEquity() int32 {
	if x != nil {
		return x.CountWithoutEquity
	}
	return 0
}

func (x *GetAccountTransactionCountRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_account_v1_account_proto protoreflect.FileDescriptor

const file_account_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x18account/v1/account.proto\x12\n" +
	"account.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fbase/base.proto\"\xbb\x04\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\tparent_id\x18\x02 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.base.AccountTypeR\x04type\x12\x19\n" +
	"\bis_group\x18\x05 \x01(\bR\aisGroup\x12%\n" +
	"\abalance\x18\x06 \x01(\v2\v.base.MoneyR\abalance\x12-\n" +
	"\x10default_child_id\x18\a \x01(\tH\x01R\x0edefaultChildId\x88\x01\x01\x12\x12\n" +
	"\x04date\x18\b \x01(\tR\x04date\x12\x16\n" +
	"\x06number\x18\t \x01(\tR\x06number\x12\x18\n" +
	"\aremarks\x18\n" +
	" \x01(\tR\aremarks\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12,\n" +
	"\x12opening_voucher_id\x18\r \x01(\tR\x10openingVoucherId\x12/\n" +
	"\x11equity_account_id\x18\x0e \x01(\tH\x02R\x0fequityAccountId\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\x13\n" +
	"\x11_default_child_idB\x14\n" +
	"\x12_equity_account_id\"\xe6\x02\n" +
	"\fAccountInput\x12 \n" +
	"\tparent_id\x18\x01 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.base.AccountTypeR\x04type\x12\x19\n" +
	"\bis_group\x18\x04 \x01(\bR\aisGroup\x12%\n" +
	"\abalance\x18\x05 \x01(\v2\v.base.MoneyR\abalance\x12-\n" +
	"\x10default_child_id\x18\x06 \x01(\tH\x01R\x0edefaultChildId\x88\x01\x01\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04date\x12\x1b\n" +
	"\x06number\x18\b \x01(\tH\x02R\x06number\x88\x01\x01\x12\x1d\n" +
	"\aremarks\x18\t \x01(\tH\x03R\aremarks\x88\x01\x01B\f\n" +
	"\n" +
	"_parent_idB\x13\n" +
	"\x11_default_child_idB\t\n" +
	"\a_numberB\n" +
	"\n" +
	"\b_remarks\"|\n" +
	"\fAccountQuery\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.base.AccountTypeR\x04type\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\"A\n" +
	"\x0fListAccountsReq\x12.\n" +
	"\x05query\x18\x01 \x01(\v2\x18.account.v1.AccountQueryR\x05query\"\x9c\x01\n" +
	"\x0fListAccountsRes\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.account.v1.AccountR\x04data\x127\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x17.base.PaginatedResponseR\n" +
	"pagination\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"B\n" +
	"\x10CreateAccountReq\x12.\n" +
	"\x05input\x18\x01 \x01(\v2\x18.account.v1.AccountInputR\x05input\"j\n" +
	"\x10CreateAccountRes\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x1f\n" +
	"\rGetAccountReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\rGetAccountRes\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"R\n" +
	"\x10UpdateAccountReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x05input\x18\x02 \x01(\v2\x18.account.v1.AccountInputR\x05input\"j\n" +
	"\x10UpdateAccountRes\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\xc8\x01\n" +
	"\x10DeleteAccountReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12_\n" +
	"\x11migration_targets\x18\x02 \x03(\v22.account.v1.DeleteAccountReq.MigrationTargetsEntryR\x10migrationTargets\x1aC\n" +
	"\x15MigrationTargetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x10DeleteAccountRes\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"/\n" +
	"\x1dGetAccountTransactionCountReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x90\x01\n" +
	"\x1dGetAccountTransactionCountRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x120\n" +
	"\x14count_without_equity\x18\x02 \x01(\x05R\x12countWithoutEquity\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base2\xf9\x03\n" +
	"\x0eAccountService\x12H\n" +
	"\fListAccounts\x12\x1b.account.v1.ListAccountsReq\x1a\x1b.account.v1.ListAccountsRes\x12K\n" +
	"\rCreateAccount\x12\x1c.account.v1.CreateAccountReq\x1a\x1c.account.v1.CreateAccountRes\x12B\n" +
	"\n" +
	"GetAccount\x12\x19.account.v1.GetAccountReq\x1a\x19.account.v1.GetAccountRes\x12K\n" +
	"\rUpdateAccount\x12\x1c.account.v1.UpdateAccountReq\x1a\x1c.account.v1.UpdateAccountRes\x12K\n" +
	"\rDeleteAccount\x12\x1c.account.v1.DeleteAccountReq\x1a\x1c.account.v1.DeleteAccountRes\x12r\n" +
	"\x1aGetAccountTransactionCount\x12).account.v1.GetAccountTransactionCountReq\x1a).account.v1.GetAccountTransactionCountResB\x1cZ\x1agaap-api/api/account/v1;v1b\x06proto3"

var (
	file_account_v1_account_proto_rawDescOnce sync.Once
	file_account_v1_account_proto_rawDescData []byte
)

func file_account_v1_account_proto_rawDescGZIP() []byte {
	file_account_v1_account_proto_rawDescOnce.Do(func() {
		file_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)))
	})
	return file_account_v1_account_proto_rawDescData
}

var file_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_account_v1_account_proto_goTypes = []any{
	(*Account)(nil),                       // 0: account.v1.Account
	(*AccountInput)(nil),                  // 1: account.v1.AccountInput
	(*AccountQuery)(nil),                  // 2: account.v1.AccountQuery
	(*ListAccountsReq)(nil),               // 3: account.v1.ListAccountsReq
	(*ListAccountsRes)(nil),               // 4: account.v1.ListAccountsRes
	(*CreateAccountReq)(nil),              // 5: account.v1.CreateAccountReq
	(*CreateAccountRes)(nil),              // 6: account.v1.CreateAccountRes
	(*GetAccountReq)(nil),                 // 7: account.v1.GetAccountReq
	(*GetAccountRes)(nil),                 // 8: account.v1.GetAccountRes
	(*UpdateAccountReq)(nil),              // 9: account.v1.UpdateAccountReq
	(*UpdateAccountRes)(nil),              // 10: account.v1.UpdateAccountRes
	(*DeleteAccountReq)(nil),              // 11: account.v1.DeleteAccountReq
	(*DeleteAccountRes)(nil),              // 12: account.v1.DeleteAccountRes
	(*GetAccountTransactionCountReq)(nil), // 13: account.v1.GetAccountTransactionCountReq
	(*GetAccountTransactionCountRes)(nil), // 14: account.v1.GetAccountTransactionCountRes
	nil,                                   // 15: account.v1.DeleteAccountReq.MigrationTargetsEntry
	(base.AccountType)(0),                 // 16: base.AccountType
	(*base.Money)(nil),                    // 17: base.Money
	(*timestamppb.Timestamp)(nil),         // 18: google.protobuf.Timestamp
	(*base.PaginatedResponse)(nil),        // 19: base.PaginatedResponse
	(*base.BaseResponse)(nil),             // 20: base.BaseResponse
}
var file_account_v1_account_proto_depIdxs = []int32{
	16, // 0: account.v1.Account.type:type_name -> base.AccountType
	17, // 1: account.v1.Account.balance:type_name -> base.Money
	18, // 2: account.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: account.v1.Account.updated_at:type_name -> google.protobuf.Timestamp
	16, // 4: account.v1.AccountInput.type:type_name -> base.AccountType
	17, // 5: account.v1.AccountInput.balance:type_name -> base.Money
	16, // 6: account.v1.AccountQuery.type:type_name -> base.AccountType
	2,  // 7: account.v1.ListAccountsReq.query:type_name -> account.v1.AccountQuery
	0,  // 8: account.v1.ListAccountsRes.data:type_name -> account.v1.Account
	19, // 9: account.v1.ListAccountsRes.pagination:type_name -> base.PaginatedResponse
	20, // 10: account.v1.ListAccountsRes.base:type_name -> base.BaseResponse
	1,  // 11: account.v1.CreateAccountReq.input:type_name -> account.v1.AccountInput
	0,  // 12: account.v1.CreateAccountRes.account:type_name -> account.v1.Account
	20, // 13: account.v1.CreateAccountRes.base:type_name -> base.BaseResponse
	0,  // 14: account.v1.GetAccountRes.account:type_name -> account.v1.Account
	20, // 15: account.v1.GetAccountRes.base:type_name -> base.BaseResponse
	1,  // 16: account.v1.UpdateAccountReq.input:type_name -> account.v1.AccountInput
	0,  // 17: account.v1.UpdateAccountRes.account:type_name -> account.v1.Account
	20, // 18: account.v1.UpdateAccountRes.base:type_name -> base.BaseResponse
	15, // 19: account.v1.DeleteAccountReq.migration_targets:type_name -> account.v1.DeleteAccountReq.MigrationTargetsEntry
	20, // 20: account.v1.DeleteAccountRes.base:type_name -> base.BaseResponse
	20, // 21: account.v1.GetAccountTransactionCountRes.base:type_name -> base.BaseResponse
	3,  // 22: account.v1.AccountService.ListAccounts:input_type -> account.v1.ListAccountsReq
	5,  // 23: account.v1.AccountService.CreateAccount:input_type -> account.v1.CreateAccountReq
	7,  // 24: account.v1.AccountService.GetAccount:input_type -> account.v1.GetAccountReq
	9,  // 25: account.v1.AccountService.UpdateAccount:input_type -> account.v1.UpdateAccountReq
	11, // 26: account.v1.AccountService.DeleteAccount:input_type -> account.v1.DeleteAccountReq
	13, // 27: account.v1.AccountService.GetAccountTransactionCount:input_type -> account.v1.GetAccountTransactionCountReq
	4,  // 28: account.v1.AccountService.ListAccounts:output_type -> account.v1.ListAccountsRes
	6,  // 29: account.v1.AccountService.CreateAccount:output_type -> account.v1.CreateAccountRes
	8,  // 30: account.v1.AccountService.GetAccount:output_type -> account.v1.GetAccountRes
	10, // 31: account.v1.AccountService.UpdateAccount:output_type -> account.v1.UpdateAccountRes
	12, // 32: account.v1.AccountService.DeleteAccount:output_type -> account.v1.DeleteAccountRes
	14, // 33: account.v1.AccountService.GetAccountTransactionCount:output_type -> account.v1.GetAccountTransactionCountRes
	28, // [28:34] is the sub-list for method output_type
	22, // [22:28] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_account_v1_account_proto_init() }
func file_account_v1_account_proto_init() {
	if File_account_v1_account_proto != nil {
		return
	}
	file_account_v1_account_proto_msgTypes[0].OneofWrappers = []any{}
	file_account_v1_account_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v1_account_proto_goTypes,
		DependencyIndexes: file_account_v1_account_proto_depIdxs,
		MessageInfos:      file_account_v1_account_proto_msgTypes,
	}.Build()
	File_account_v1_account_proto = out.File
	file_account_v1_account_proto_goTypes = nil
	file_account_v1_account_proto_depIdxs = nil
}
