// Code generated by genctrl. DO NOT EDIT.
// Source: account/v1/account.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for AccountService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfListAccountsReq is the GoFrame-compatible request wrapper for ListAccounts
type GfListAccountsReq struct {
	g.Meta `path:"/v1/account/list-accounts" method:"POST" tags:"account" summary:"List all accounts"`
	ListAccountsReq
}

// GfListAccountsRes is the GoFrame-compatible response wrapper for ListAccounts
type GfListAccountsRes = ListAccountsRes


// GfCreateAccountReq is the GoFrame-compatible request wrapper for CreateAccount
type GfCreateAccountReq struct {
	g.Meta `path:"/v1/account/create-account" method:"POST" tags:"account" summary:"Create a new account"`
	CreateAccountReq
}

// GfCreateAccountRes is the GoFrame-compatible response wrapper for CreateAccount
type GfCreateAccountRes = CreateAccountRes


// GfGetAccountReq is the GoFrame-compatible request wrapper for GetAccount
type GfGetAccountReq struct {
	g.Meta `path:"/v1/account/get-account" method:"POST" tags:"account" summary:"Get account details"`
	GetAccountReq
}

// GfGetAccountRes is the GoFrame-compatible response wrapper for GetAccount
type GfGetAccountRes = GetAccountRes


// GfUpdateAccountReq is the GoFrame-compatible request wrapper for UpdateAccount
type GfUpdateAccountReq struct {
	g.Meta `path:"/v1/account/update-account" method:"POST" tags:"account" summary:"Update account"`
	UpdateAccountReq
}

// GfUpdateAccountRes is the GoFrame-compatible response wrapper for UpdateAccount
type GfUpdateAccountRes = UpdateAccountRes


// GfDeleteAccountReq is the GoFrame-compatible request wrapper for DeleteAccount
type GfDeleteAccountReq struct {
	g.Meta `path:"/v1/account/delete-account" method:"POST" tags:"account" summary:"Delete account with optional migration"`
	DeleteAccountReq
}

// GfDeleteAccountRes is the GoFrame-compatible response wrapper for DeleteAccount
type GfDeleteAccountRes = DeleteAccountRes


// GfGetAccountTransactionCountReq is the GoFrame-compatible request wrapper for GetAccountTransactionCount
type GfGetAccountTransactionCountReq struct {
	g.Meta `path:"/v1/account/get-account-transaction-count" method:"POST" tags:"account" summary:"Get transaction count for account"`
	GetAccountTransactionCountReq
}

// GfGetAccountTransactionCountRes is the GoFrame-compatible response wrapper for GetAccountTransactionCount
type GfGetAccountTransactionCountRes = GetAccountTransactionCountRes


