// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: data/v1/data.proto

package v1

import (
	base "gaap-api/api/base"
	v1 "gaap-api/api/task/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportParams) Reset() {
	*x = ExportParams{}
	mi := &file_data_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportParams) ProtoMessage() {}

func (x *ExportParams) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportParams.ProtoReflect.Descriptor instead.
func (*ExportParams) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *ExportParams) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ExportParams) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ExportDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *ExportParams          `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataReq) Reset() {
	*x = ExportDataReq{}
	mi := &file_data_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataReq) ProtoMessage() {}

func (x *ExportDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataReq.ProtoReflect.Descriptor instead.
func (*ExportDataReq) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *ExportDataReq) GetParams() *ExportParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExportDataRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataRes) Reset() {
	*x = ExportDataRes{}
	mi := &file_data_v1_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataRes) ProtoMessage() {}

func (x *ExportDataRes) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataRes.ProtoReflect.Descriptor instead.
func (*ExportDataRes) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{2}
}

func (x *ExportDataRes) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExportDataRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type ImportDataReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// File content in bytes
	FileContent   []byte `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty" dc:"File content in bytes"`
	FileName      string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDataReq) Reset() {
	*x = ImportDataReq{}
	mi := &file_data_v1_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDataReq) ProtoMessage() {}

func (x *ImportDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDataReq.ProtoReflect.Descriptor instead.
func (*ImportDataReq) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{3}
}

func (x *ImportDataReq) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

func (x *ImportDataReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type ImportDataRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportDataRes) Reset() {
	*x = ImportDataRes{}
	mi := &file_data_v1_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportDataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDataRes) ProtoMessage() {}

func (x *ImportDataRes) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDataRes.ProtoReflect.Descriptor instead.
func (*ImportDataRes) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{4}
}

func (x *ImportDataRes) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ImportDataRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type DownloadExportReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadExportReq) Reset() {
	*x = DownloadExportReq{}
	mi := &file_data_v1_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportReq) ProtoMessage() {}

func (x *DownloadExportReq) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportReq.ProtoReflect.Descriptor instead.
func (*DownloadExportReq) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadExportReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DownloadExportRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty" dc:"Metadata could be added here"` // Metadata could be added here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadExportRes) Reset() {
	*x = DownloadExportRes{}
	mi := &file_data_v1_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportRes) ProtoMessage() {}

func (x *DownloadExportRes) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportRes.ProtoReflect.Descriptor instead.
func (*DownloadExportRes) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadExportRes) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type GetExportStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportStatusReq) Reset() {
	*x = GetExportStatusReq{}
	mi := &file_data_v1_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportStatusReq) ProtoMessage() {}

func (x *GetExportStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportStatusReq.ProtoReflect.Descriptor instead.
func (*GetExportStatusReq) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{7}
}

func (x *GetExportStatusReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetExportStatusRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *v1.Task               `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExportStatusRes) Reset() {
	*x = GetExportStatusRes{}
	mi := &file_data_v1_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportStatusRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportStatusRes) ProtoMessage() {}

func (x *GetExportStatusRes) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportStatusRes.ProtoReflect.Descriptor instead.
func (*GetExportStatusRes) Descriptor() ([]byte, []int) {
	return file_data_v1_data_proto_rawDescGZIP(), []int{8}
}

func (x *GetExportStatusRes) GetTask() *v1.Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetExportStatusRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_data_v1_data_proto protoreflect.FileDescriptor

const file_data_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x12data/v1/data.proto\x12\adata.v1\x1a\x0fbase/base.proto\x1a\x12task/v1/task.proto\"H\n" +
	"\fExportParams\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\">\n" +
	"\rExportDataReq\x12-\n" +
	"\x06params\x18\x01 \x01(\v2\x15.data.v1.ExportParamsR\x06params\"Q\n" +
	"\rExportDataRes\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"O\n" +
	"\rImportDataReq\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\"Q\n" +
	"\rImportDataRes\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\",\n" +
	"\x11DownloadExportReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"6\n" +
	"\x11DownloadExportRes\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\"-\n" +
	"\x12GetExportStatusReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"`\n" +
	"\x12GetExportStatusRes\x12!\n" +
	"\x04task\x18\x01 \x01(\v2\r.task.v1.TaskR\x04task\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base2\xa0\x02\n" +
	"\vDataService\x12<\n" +
	"\n" +
	"ExportData\x12\x16.data.v1.ExportDataReq\x1a\x16.data.v1.ExportDataRes\x12<\n" +
	"\n" +
	"ImportData\x12\x16.data.v1.ImportDataReq\x1a\x16.data.v1.ImportDataRes\x12H\n" +
	"\x0eDownloadExport\x12\x1a.data.v1.DownloadExportReq\x1a\x1a.data.v1.DownloadExportRes\x12K\n" +
	"\x0fGetExportStatus\x12\x1b.data.v1.GetExportStatusReq\x1a\x1b.data.v1.GetExportStatusResB\x19Z\x17gaap-api/api/data/v1;v1b\x06proto3"

var (
	file_data_v1_data_proto_rawDescOnce sync.Once
	file_data_v1_data_proto_rawDescData []byte
)

func file_data_v1_data_proto_rawDescGZIP() []byte {
	file_data_v1_data_proto_rawDescOnce.Do(func() {
		file_data_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_v1_data_proto_rawDesc), len(file_data_v1_data_proto_rawDesc)))
	})
	return file_data_v1_data_proto_rawDescData
}

var file_data_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_data_v1_data_proto_goTypes = []any{
	(*ExportParams)(nil),       // 0: data.v1.ExportParams
	(*ExportDataReq)(nil),      // 1: data.v1.ExportDataReq
	(*ExportDataRes)(nil),      // 2: data.v1.ExportDataRes
	(*ImportDataReq)(nil),      // 3: data.v1.ImportDataReq
	(*ImportDataRes)(nil),      // 4: data.v1.ImportDataRes
	(*DownloadExportReq)(nil),  // 5: data.v1.DownloadExportReq
	(*DownloadExportRes)(nil),  // 6: data.v1.DownloadExportRes
	(*GetExportStatusReq)(nil), // 7: data.v1.GetExportStatusReq
	(*GetExportStatusRes)(nil), // 8: data.v1.GetExportStatusRes
	(*base.BaseResponse)(nil),  // 9: base.BaseResponse
	(*v1.Task)(nil),            // 10: task.v1.Task
}
var file_data_v1_data_proto_depIdxs = []int32{
	0,  // 0: data.v1.ExportDataReq.params:type_name -> data.v1.ExportParams
	9,  // 1: data.v1.ExportDataRes.base:type_name -> base.BaseResponse
	9,  // 2: data.v1.ImportDataRes.base:type_name -> base.BaseResponse
	10, // 3: data.v1.GetExportStatusRes.task:type_name -> task.v1.Task
	9,  // 4: data.v1.GetExportStatusRes.base:type_name -> base.BaseResponse
	1,  // 5: data.v1.DataService.ExportData:input_type -> data.v1.ExportDataReq
	3,  // 6: data.v1.DataService.ImportData:input_type -> data.v1.ImportDataReq
	5,  // 7: data.v1.DataService.DownloadExport:input_type -> data.v1.DownloadExportReq
	7,  // 8: data.v1.DataService.GetExportStatus:input_type -> data.v1.GetExportStatusReq
	2,  // 9: data.v1.DataService.ExportData:output_type -> data.v1.ExportDataRes
	4,  // 10: data.v1.DataService.ImportData:output_type -> data.v1.ImportDataRes
	6,  // 11: data.v1.DataService.DownloadExport:output_type -> data.v1.DownloadExportRes
	8,  // 12: data.v1.DataService.GetExportStatus:output_type -> data.v1.GetExportStatusRes
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_data_v1_data_proto_init() }
func file_data_v1_data_proto_init() {
	if File_data_v1_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_v1_data_proto_rawDesc), len(file_data_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_v1_data_proto_goTypes,
		DependencyIndexes: file_data_v1_data_proto_depIdxs,
		MessageInfos:      file_data_v1_data_proto_msgTypes,
	}.Build()
	File_data_v1_data_proto = out.File
	file_data_v1_data_proto_goTypes = nil
	file_data_v1_data_proto_depIdxs = nil
}
