// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: data/v1/data.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_ExportData_FullMethodName      = "/data.v1.DataService/ExportData"
	DataService_ImportData_FullMethodName      = "/data.v1.DataService/ImportData"
	DataService_DownloadExport_FullMethodName  = "/data.v1.DataService/DownloadExport"
	DataService_GetExportStatus_FullMethodName = "/data.v1.DataService/GetExportStatus"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	// Create data export task
	ExportData(ctx context.Context, in *ExportDataReq, opts ...grpc.CallOption) (*ExportDataRes, error)
	// Create data import task
	ImportData(ctx context.Context, in *ImportDataReq, opts ...grpc.CallOption) (*ImportDataRes, error)
	// Download export file
	// Note: Streaming RPC might be better for large files, but keeping simple for request/response migration
	DownloadExport(ctx context.Context, in *DownloadExportReq, opts ...grpc.CallOption) (*DownloadExportRes, error)
	// Get export task status
	GetExportStatus(ctx context.Context, in *GetExportStatusReq, opts ...grpc.CallOption) (*GetExportStatusRes, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) ExportData(ctx context.Context, in *ExportDataReq, opts ...grpc.CallOption) (*ExportDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportDataRes)
	err := c.cc.Invoke(ctx, DataService_ExportData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ImportData(ctx context.Context, in *ImportDataReq, opts ...grpc.CallOption) (*ImportDataRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportDataRes)
	err := c.cc.Invoke(ctx, DataService_ImportData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) DownloadExport(ctx context.Context, in *DownloadExportReq, opts ...grpc.CallOption) (*DownloadExportRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadExportRes)
	err := c.cc.Invoke(ctx, DataService_DownloadExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) GetExportStatus(ctx context.Context, in *GetExportStatusReq, opts ...grpc.CallOption) (*GetExportStatusRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExportStatusRes)
	err := c.cc.Invoke(ctx, DataService_GetExportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	// Create data export task
	ExportData(context.Context, *ExportDataReq) (*ExportDataRes, error)
	// Create data import task
	ImportData(context.Context, *ImportDataReq) (*ImportDataRes, error)
	// Download export file
	// Note: Streaming RPC might be better for large files, but keeping simple for request/response migration
	DownloadExport(context.Context, *DownloadExportReq) (*DownloadExportRes, error)
	// Get export task status
	GetExportStatus(context.Context, *GetExportStatusReq) (*GetExportStatusRes, error)
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) ExportData(context.Context, *ExportDataReq) (*ExportDataRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportData not implemented")
}
func (UnimplementedDataServiceServer) ImportData(context.Context, *ImportDataReq) (*ImportDataRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportData not implemented")
}
func (UnimplementedDataServiceServer) DownloadExport(context.Context, *DownloadExportReq) (*DownloadExportRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadExport not implemented")
}
func (UnimplementedDataServiceServer) GetExportStatus(context.Context, *GetExportStatusReq) (*GetExportStatusRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExportStatus not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_ExportData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ExportData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ExportData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ExportData(ctx, req.(*ExportDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ImportData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ImportData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ImportData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ImportData(ctx, req.(*ImportDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_DownloadExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).DownloadExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_DownloadExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).DownloadExport(ctx, req.(*DownloadExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_GetExportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).GetExportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_GetExportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).GetExportStatus(ctx, req.(*GetExportStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.v1.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportData",
			Handler:    _DataService_ExportData_Handler,
		},
		{
			MethodName: "ImportData",
			Handler:    _DataService_ImportData_Handler,
		},
		{
			MethodName: "DownloadExport",
			Handler:    _DataService_DownloadExport_Handler,
		},
		{
			MethodName: "GetExportStatus",
			Handler:    _DataService_GetExportStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data/v1/data.proto",
}
