// Code generated by genctrl. DO NOT EDIT.
// Source: data/v1/data.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for DataService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfExportDataReq is the GoFrame-compatible request wrapper for ExportData
type GfExportDataReq struct {
	g.Meta `path:"/data/export-data" method:"POST" tags:"data" summary:"Create data export task"`
	*ExportDataReq
}

// GfExportDataRes is the GoFrame-compatible response wrapper for ExportData
type GfExportDataRes = ExportDataRes


// GfImportDataReq is the GoFrame-compatible request wrapper for ImportData
type GfImportDataReq struct {
	g.Meta `path:"/data/import-data" method:"POST" tags:"data" summary:"Create data import task"`
	*ImportDataReq
}

// GfImportDataRes is the GoFrame-compatible response wrapper for ImportData
type GfImportDataRes = ImportDataRes


// GfDownloadExportReq is the GoFrame-compatible request wrapper for DownloadExport
type GfDownloadExportReq struct {
	g.Meta `path:"/data/download-export" method:"POST" tags:"data" summary:"Note: Streaming RPC might be better for large files, but keeping simple for request/response migration"`
	*DownloadExportReq
}

// GfDownloadExportRes is the GoFrame-compatible response wrapper for DownloadExport
type GfDownloadExportRes = DownloadExportRes


// GfGetExportStatusReq is the GoFrame-compatible request wrapper for GetExportStatus
type GfGetExportStatusReq struct {
	g.Meta `path:"/data/export-status" method:"GET" tags:"data" summary:"Get export task status"`
	*GetExportStatusReq
}

// GfGetExportStatusRes is the GoFrame-compatible response wrapper for GetExportStatus
type GfGetExportStatusRes = GetExportStatusRes


