// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: dashboard/v1/dashboard.proto

package v1

import (
	base "gaap-api/api/base"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        *base.Money            `protobuf:"bytes,1,opt,name=assets,proto3" json:"assets,omitempty"`
	Liabilities   *base.Money            `protobuf:"bytes,2,opt,name=liabilities,proto3" json:"liabilities,omitempty"`
	NetWorth      *base.Money            `protobuf:"bytes,3,opt,name=net_worth,json=netWorth,proto3" json:"net_worth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardSummary) Reset() {
	*x = DashboardSummary{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSummary) ProtoMessage() {}

func (x *DashboardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSummary.ProtoReflect.Descriptor instead.
func (*DashboardSummary) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardSummary) GetAssets() *base.Money {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *DashboardSummary) GetLiabilities() *base.Money {
	if x != nil {
		return x.Liabilities
	}
	return nil
}

func (x *DashboardSummary) GetNetWorth() *base.Money {
	if x != nil {
		return x.NetWorth
	}
	return nil
}

type MonthlyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Income        *base.Money            `protobuf:"bytes,1,opt,name=income,proto3" json:"income,omitempty"`
	Expense       *base.Money            `protobuf:"bytes,2,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyStats) Reset() {
	*x = MonthlyStats{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyStats) ProtoMessage() {}

func (x *MonthlyStats) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyStats.ProtoReflect.Descriptor instead.
func (*MonthlyStats) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *MonthlyStats) GetIncome() *base.Money {
	if x != nil {
		return x.Income
	}
	return nil
}

func (x *MonthlyStats) GetExpense() *base.Money {
	if x != nil {
		return x.Expense
	}
	return nil
}

type DailyBalance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Date string
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty" dc:"Date string"`
	// Account ID -> Balance
	Balances      map[string]*base.Money `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" dc:"Account ID -> Balance"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyBalance) Reset() {
	*x = DailyBalance{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyBalance) ProtoMessage() {}

func (x *DailyBalance) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyBalance.ProtoReflect.Descriptor instead.
func (*DailyBalance) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *DailyBalance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyBalance) GetBalances() map[string]*base.Money {
	if x != nil {
		return x.Balances
	}
	return nil
}

type GetDashboardSummaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardSummaryReq) Reset() {
	*x = GetDashboardSummaryReq{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryReq) ProtoMessage() {}

func (x *GetDashboardSummaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryReq.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryReq) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

type GetDashboardSummaryRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *DashboardSummary      `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardSummaryRes) Reset() {
	*x = GetDashboardSummaryRes{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryRes) ProtoMessage() {}

func (x *GetDashboardSummaryRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryRes.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryRes) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *GetDashboardSummaryRes) GetSummary() *DashboardSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetDashboardSummaryRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetMonthlyStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyStatsReq) Reset() {
	*x = GetMonthlyStatsReq{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyStatsReq) ProtoMessage() {}

func (x *GetMonthlyStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyStatsReq.ProtoReflect.Descriptor instead.
func (*GetMonthlyStatsReq) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{5}
}

type GetMonthlyStatsRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *MonthlyStats          `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyStatsRes) Reset() {
	*x = GetMonthlyStatsRes{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyStatsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyStatsRes) ProtoMessage() {}

func (x *GetMonthlyStatsRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyStatsRes.ProtoReflect.Descriptor instead.
func (*GetMonthlyStatsRes) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *GetMonthlyStatsRes) GetStats() *MonthlyStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetMonthlyStatsRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetBalanceTrendReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []string               `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceTrendReq) Reset() {
	*x = GetBalanceTrendReq{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceTrendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceTrendReq) ProtoMessage() {}

func (x *GetBalanceTrendReq) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceTrendReq.ProtoReflect.Descriptor instead.
func (*GetBalanceTrendReq) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *GetBalanceTrendReq) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetBalanceTrendRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*DailyBalance        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceTrendRes) Reset() {
	*x = GetBalanceTrendRes{}
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceTrendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceTrendRes) ProtoMessage() {}

func (x *GetBalanceTrendRes) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_v1_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceTrendRes.ProtoReflect.Descriptor instead.
func (*GetBalanceTrendRes) Descriptor() ([]byte, []int) {
	return file_dashboard_v1_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalanceTrendRes) GetData() []*DailyBalance {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBalanceTrendRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_dashboard_v1_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x1cdashboard/v1/dashboard.proto\x12\fdashboard.v1\x1a\x0fbase/base.proto\"\x90\x01\n" +
	"\x10DashboardSummary\x12#\n" +
	"\x06assets\x18\x01 \x01(\v2\v.base.MoneyR\x06assets\x12-\n" +
	"\vliabilities\x18\x02 \x01(\v2\v.base.MoneyR\vliabilities\x12(\n" +
	"\tnet_worth\x18\x03 \x01(\v2\v.base.MoneyR\bnetWorth\"Z\n" +
	"\fMonthlyStats\x12#\n" +
	"\x06income\x18\x01 \x01(\v2\v.base.MoneyR\x06income\x12%\n" +
	"\aexpense\x18\x02 \x01(\v2\v.base.MoneyR\aexpense\"\xb2\x01\n" +
	"\fDailyBalance\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12D\n" +
	"\bbalances\x18\x02 \x03(\v2(.dashboard.v1.DailyBalance.BalancesEntryR\bbalances\x1aH\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.base.MoneyR\x05value:\x028\x01\"\x18\n" +
	"\x16GetDashboardSummaryReq\"{\n" +
	"\x16GetDashboardSummaryRes\x128\n" +
	"\asummary\x18\x01 \x01(\v2\x1e.dashboard.v1.DashboardSummaryR\asummary\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x14\n" +
	"\x12GetMonthlyStatsReq\"o\n" +
	"\x12GetMonthlyStatsRes\x120\n" +
	"\x05stats\x18\x01 \x01(\v2\x1a.dashboard.v1.MonthlyStatsR\x05stats\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"0\n" +
	"\x12GetBalanceTrendReq\x12\x1a\n" +
	"\baccounts\x18\x01 \x03(\tR\baccounts\"m\n" +
	"\x12GetBalanceTrendRes\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.dashboard.v1.DailyBalanceR\x04data\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base2\xa3\x02\n" +
	"\x10DashboardService\x12a\n" +
	"\x13GetDashboardSummary\x12$.dashboard.v1.GetDashboardSummaryReq\x1a$.dashboard.v1.GetDashboardSummaryRes\x12U\n" +
	"\x0fGetMonthlyStats\x12 .dashboard.v1.GetMonthlyStatsReq\x1a .dashboard.v1.GetMonthlyStatsRes\x12U\n" +
	"\x0fGetBalanceTrend\x12 .dashboard.v1.GetBalanceTrendReq\x1a .dashboard.v1.GetBalanceTrendResB\x1eZ\x1cgaap-api/api/dashboard/v1;v1b\x06proto3"

var (
	file_dashboard_v1_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_v1_dashboard_proto_rawDescData []byte
)

func file_dashboard_v1_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_v1_dashboard_proto_rawDesc), len(file_dashboard_v1_dashboard_proto_rawDesc)))
	})
	return file_dashboard_v1_dashboard_proto_rawDescData
}

var file_dashboard_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dashboard_v1_dashboard_proto_goTypes = []any{
	(*DashboardSummary)(nil),       // 0: dashboard.v1.DashboardSummary
	(*MonthlyStats)(nil),           // 1: dashboard.v1.MonthlyStats
	(*DailyBalance)(nil),           // 2: dashboard.v1.DailyBalance
	(*GetDashboardSummaryReq)(nil), // 3: dashboard.v1.GetDashboardSummaryReq
	(*GetDashboardSummaryRes)(nil), // 4: dashboard.v1.GetDashboardSummaryRes
	(*GetMonthlyStatsReq)(nil),     // 5: dashboard.v1.GetMonthlyStatsReq
	(*GetMonthlyStatsRes)(nil),     // 6: dashboard.v1.GetMonthlyStatsRes
	(*GetBalanceTrendReq)(nil),     // 7: dashboard.v1.GetBalanceTrendReq
	(*GetBalanceTrendRes)(nil),     // 8: dashboard.v1.GetBalanceTrendRes
	nil,                            // 9: dashboard.v1.DailyBalance.BalancesEntry
	(*base.Money)(nil),             // 10: base.Money
	(*base.BaseResponse)(nil),      // 11: base.BaseResponse
}
var file_dashboard_v1_dashboard_proto_depIdxs = []int32{
	10, // 0: dashboard.v1.DashboardSummary.assets:type_name -> base.Money
	10, // 1: dashboard.v1.DashboardSummary.liabilities:type_name -> base.Money
	10, // 2: dashboard.v1.DashboardSummary.net_worth:type_name -> base.Money
	10, // 3: dashboard.v1.MonthlyStats.income:type_name -> base.Money
	10, // 4: dashboard.v1.MonthlyStats.expense:type_name -> base.Money
	9,  // 5: dashboard.v1.DailyBalance.balances:type_name -> dashboard.v1.DailyBalance.BalancesEntry
	0,  // 6: dashboard.v1.GetDashboardSummaryRes.summary:type_name -> dashboard.v1.DashboardSummary
	11, // 7: dashboard.v1.GetDashboardSummaryRes.base:type_name -> base.BaseResponse
	1,  // 8: dashboard.v1.GetMonthlyStatsRes.stats:type_name -> dashboard.v1.MonthlyStats
	11, // 9: dashboard.v1.GetMonthlyStatsRes.base:type_name -> base.BaseResponse
	2,  // 10: dashboard.v1.GetBalanceTrendRes.data:type_name -> dashboard.v1.DailyBalance
	11, // 11: dashboard.v1.GetBalanceTrendRes.base:type_name -> base.BaseResponse
	10, // 12: dashboard.v1.DailyBalance.BalancesEntry.value:type_name -> base.Money
	3,  // 13: dashboard.v1.DashboardService.GetDashboardSummary:input_type -> dashboard.v1.GetDashboardSummaryReq
	5,  // 14: dashboard.v1.DashboardService.GetMonthlyStats:input_type -> dashboard.v1.GetMonthlyStatsReq
	7,  // 15: dashboard.v1.DashboardService.GetBalanceTrend:input_type -> dashboard.v1.GetBalanceTrendReq
	4,  // 16: dashboard.v1.DashboardService.GetDashboardSummary:output_type -> dashboard.v1.GetDashboardSummaryRes
	6,  // 17: dashboard.v1.DashboardService.GetMonthlyStats:output_type -> dashboard.v1.GetMonthlyStatsRes
	8,  // 18: dashboard.v1.DashboardService.GetBalanceTrend:output_type -> dashboard.v1.GetBalanceTrendRes
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_dashboard_v1_dashboard_proto_init() }
func file_dashboard_v1_dashboard_proto_init() {
	if File_dashboard_v1_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_v1_dashboard_proto_rawDesc), len(file_dashboard_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dashboard_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_v1_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_v1_dashboard_proto = out.File
	file_dashboard_v1_dashboard_proto_goTypes = nil
	file_dashboard_v1_dashboard_proto_depIdxs = nil
}
