// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: dashboard/v1/dashboard.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DashboardService_GetDashboardSummary_FullMethodName = "/dashboard.v1.DashboardService/GetDashboardSummary"
	DashboardService_GetMonthlyStats_FullMethodName     = "/dashboard.v1.DashboardService/GetMonthlyStats"
	DashboardService_GetBalanceTrend_FullMethodName     = "/dashboard.v1.DashboardService/GetBalanceTrend"
)

// DashboardServiceClient is the client API for DashboardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DashboardServiceClient interface {
	// Get dashboard summary
	GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryReq, opts ...grpc.CallOption) (*GetDashboardSummaryRes, error)
	// Get monthly income and expense statistics
	GetMonthlyStats(ctx context.Context, in *GetMonthlyStatsReq, opts ...grpc.CallOption) (*GetMonthlyStatsRes, error)
	// Get balance trend data
	GetBalanceTrend(ctx context.Context, in *GetBalanceTrendReq, opts ...grpc.CallOption) (*GetBalanceTrendRes, error)
}

type dashboardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDashboardServiceClient(cc grpc.ClientConnInterface) DashboardServiceClient {
	return &dashboardServiceClient{cc}
}

func (c *dashboardServiceClient) GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryReq, opts ...grpc.CallOption) (*GetDashboardSummaryRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardSummaryRes)
	err := c.cc.Invoke(ctx, DashboardService_GetDashboardSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetMonthlyStats(ctx context.Context, in *GetMonthlyStatsReq, opts ...grpc.CallOption) (*GetMonthlyStatsRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonthlyStatsRes)
	err := c.cc.Invoke(ctx, DashboardService_GetMonthlyStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dashboardServiceClient) GetBalanceTrend(ctx context.Context, in *GetBalanceTrendReq, opts ...grpc.CallOption) (*GetBalanceTrendRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceTrendRes)
	err := c.cc.Invoke(ctx, DashboardService_GetBalanceTrend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DashboardServiceServer is the server API for DashboardService service.
// All implementations must embed UnimplementedDashboardServiceServer
// for forward compatibility.
type DashboardServiceServer interface {
	// Get dashboard summary
	GetDashboardSummary(context.Context, *GetDashboardSummaryReq) (*GetDashboardSummaryRes, error)
	// Get monthly income and expense statistics
	GetMonthlyStats(context.Context, *GetMonthlyStatsReq) (*GetMonthlyStatsRes, error)
	// Get balance trend data
	GetBalanceTrend(context.Context, *GetBalanceTrendReq) (*GetBalanceTrendRes, error)
	mustEmbedUnimplementedDashboardServiceServer()
}

// UnimplementedDashboardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDashboardServiceServer struct{}

func (UnimplementedDashboardServiceServer) GetDashboardSummary(context.Context, *GetDashboardSummaryReq) (*GetDashboardSummaryRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboardSummary not implemented")
}
func (UnimplementedDashboardServiceServer) GetMonthlyStats(context.Context, *GetMonthlyStatsReq) (*GetMonthlyStatsRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonthlyStats not implemented")
}
func (UnimplementedDashboardServiceServer) GetBalanceTrend(context.Context, *GetBalanceTrendReq) (*GetBalanceTrendRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalanceTrend not implemented")
}
func (UnimplementedDashboardServiceServer) mustEmbedUnimplementedDashboardServiceServer() {}
func (UnimplementedDashboardServiceServer) testEmbeddedByValue()                          {}

// UnsafeDashboardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DashboardServiceServer will
// result in compilation errors.
type UnsafeDashboardServiceServer interface {
	mustEmbedUnimplementedDashboardServiceServer()
}

func RegisterDashboardServiceServer(s grpc.ServiceRegistrar, srv DashboardServiceServer) {
	// If the following call panics, it indicates UnimplementedDashboardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DashboardService_ServiceDesc, srv)
}

func _DashboardService_GetDashboardSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetDashboardSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetDashboardSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetDashboardSummary(ctx, req.(*GetDashboardSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetMonthlyStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetMonthlyStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetMonthlyStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetMonthlyStats(ctx, req.(*GetMonthlyStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DashboardService_GetBalanceTrend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceTrendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DashboardServiceServer).GetBalanceTrend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DashboardService_GetBalanceTrend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DashboardServiceServer).GetBalanceTrend(ctx, req.(*GetBalanceTrendReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DashboardService_ServiceDesc is the grpc.ServiceDesc for DashboardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DashboardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dashboard.v1.DashboardService",
	HandlerType: (*DashboardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDashboardSummary",
			Handler:    _DashboardService_GetDashboardSummary_Handler,
		},
		{
			MethodName: "GetMonthlyStats",
			Handler:    _DashboardService_GetMonthlyStats_Handler,
		},
		{
			MethodName: "GetBalanceTrend",
			Handler:    _DashboardService_GetBalanceTrend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dashboard/v1/dashboard.proto",
}
