// Code generated by genctrl. DO NOT EDIT.
// Source: dashboard/v1/dashboard.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for DashboardService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfGetDashboardSummaryReq is the GoFrame-compatible request wrapper for GetDashboardSummary
type GfGetDashboardSummaryReq struct {
	g.Meta `path:"/v1/dashboard/get-dashboard-summary" method:"POST" tags:"dashboard" summary:"Get dashboard summary"`
	GetDashboardSummaryReq
}

// GfGetDashboardSummaryRes is the GoFrame-compatible response wrapper for GetDashboardSummary
type GfGetDashboardSummaryRes = GetDashboardSummaryRes


// GfGetMonthlyStatsReq is the GoFrame-compatible request wrapper for GetMonthlyStats
type GfGetMonthlyStatsReq struct {
	g.Meta `path:"/v1/dashboard/get-monthly-stats" method:"POST" tags:"dashboard" summary:"Get monthly income and expense statistics"`
	GetMonthlyStatsReq
}

// GfGetMonthlyStatsRes is the GoFrame-compatible response wrapper for GetMonthlyStats
type GfGetMonthlyStatsRes = GetMonthlyStatsRes


// GfGetBalanceTrendReq is the GoFrame-compatible request wrapper for GetBalanceTrend
type GfGetBalanceTrendReq struct {
	g.Meta `path:"/v1/dashboard/get-balance-trend" method:"POST" tags:"dashboard" summary:"Get balance trend data"`
	GetBalanceTrendReq
}

// GfGetBalanceTrendRes is the GoFrame-compatible response wrapper for GetBalanceTrend
type GfGetBalanceTrendRes = GetBalanceTrendRes


