// Code generated by genctrl. DO NOT EDIT.
// Source: config/v1/config.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for ConfigService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfListCurrenciesReq is the GoFrame-compatible request wrapper for ListCurrencies
type GfListCurrenciesReq struct {
	g.Meta `path:"/v1/config/list-currencies" method:"POST" tags:"config" summary:"Get supported currencies"`
	ListCurrenciesReq
}

// GfListCurrenciesRes is the GoFrame-compatible response wrapper for ListCurrencies
type GfListCurrenciesRes = ListCurrenciesRes


// GfAddCurrencyReq is the GoFrame-compatible request wrapper for AddCurrency
type GfAddCurrencyReq struct {
	g.Meta `path:"/v1/config/add-currency" method:"POST" tags:"config" summary:"Add a supported currency"`
	AddCurrencyReq
}

// GfAddCurrencyRes is the GoFrame-compatible response wrapper for AddCurrency
type GfAddCurrencyRes = AddCurrencyRes


// GfDeleteCurrencyReq is the GoFrame-compatible request wrapper for DeleteCurrency
type GfDeleteCurrencyReq struct {
	g.Meta `path:"/v1/config/delete-currency" method:"POST" tags:"config" summary:"Remove a supported currency"`
	DeleteCurrencyReq
}

// GfDeleteCurrencyRes is the GoFrame-compatible response wrapper for DeleteCurrency
type GfDeleteCurrencyRes = DeleteCurrencyRes


// GfGetThemesReq is the GoFrame-compatible request wrapper for GetThemes
type GfGetThemesReq struct {
	g.Meta `path:"/v1/config/get-themes" method:"POST" tags:"config" summary:"Get available themes"`
	GetThemesReq
}

// GfGetThemesRes is the GoFrame-compatible response wrapper for GetThemes
type GfGetThemesRes = GetThemesRes


// GfGetAccountTypesReq is the GoFrame-compatible request wrapper for GetAccountTypes
type GfGetAccountTypesReq struct {
	g.Meta `path:"/v1/config/get-account-types" method:"POST" tags:"config" summary:"Get account type definitions"`
	GetAccountTypesReq
}

// GfGetAccountTypesRes is the GoFrame-compatible response wrapper for GetAccountTypes
type GfGetAccountTypesRes = GetAccountTypesRes


