// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: config/v1/config.proto

package v1

import (
	base "gaap-api/api/base"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCurrenciesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesReq) Reset() {
	*x = ListCurrenciesReq{}
	mi := &file_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesReq) ProtoMessage() {}

func (x *ListCurrenciesReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesReq.ProtoReflect.Descriptor instead.
func (*ListCurrenciesReq) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

type ListCurrenciesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	Currencies    []string               `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesRes) Reset() {
	*x = ListCurrenciesRes{}
	mi := &file_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesRes) ProtoMessage() {}

func (x *ListCurrenciesRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesRes.ProtoReflect.Descriptor instead.
func (*ListCurrenciesRes) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ListCurrenciesRes) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *ListCurrenciesRes) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *ListCurrenciesRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type AddCurrencyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCurrencyReq) Reset() {
	*x = AddCurrencyReq{}
	mi := &file_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCurrencyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCurrencyReq) ProtoMessage() {}

func (x *AddCurrencyReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCurrencyReq.ProtoReflect.Descriptor instead.
func (*AddCurrencyReq) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *AddCurrencyReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AddCurrencyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codes         []string               `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	Currencies    []string               `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCurrencyRes) Reset() {
	*x = AddCurrencyRes{}
	mi := &file_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCurrencyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCurrencyRes) ProtoMessage() {}

func (x *AddCurrencyRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCurrencyRes.ProtoReflect.Descriptor instead.
func (*AddCurrencyRes) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *AddCurrencyRes) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *AddCurrencyRes) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *AddCurrencyRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type DeleteCurrencyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyReq) Reset() {
	*x = DeleteCurrencyReq{}
	mi := &file_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyReq) ProtoMessage() {}

func (x *DeleteCurrencyReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyReq.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyReq) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCurrencyReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeleteCurrencyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyRes) Reset() {
	*x = DeleteCurrencyRes{}
	mi := &file_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyRes) ProtoMessage() {}

func (x *DeleteCurrencyRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyRes.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyRes) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCurrencyRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetThemesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThemesReq) Reset() {
	*x = GetThemesReq{}
	mi := &file_config_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThemesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThemesReq) ProtoMessage() {}

func (x *GetThemesReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThemesReq.ProtoReflect.Descriptor instead.
func (*GetThemesReq) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{6}
}

type GetThemesRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Themes        []*base.Theme          `protobuf:"bytes,1,rep,name=themes,proto3" json:"themes,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThemesRes) Reset() {
	*x = GetThemesRes{}
	mi := &file_config_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThemesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThemesRes) ProtoMessage() {}

func (x *GetThemesRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThemesRes.ProtoReflect.Descriptor instead.
func (*GetThemesRes) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *GetThemesRes) GetThemes() []*base.Theme {
	if x != nil {
		return x.Themes
	}
	return nil
}

func (x *GetThemesRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetAccountTypesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTypesReq) Reset() {
	*x = GetAccountTypesReq{}
	mi := &file_config_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTypesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTypesReq) ProtoMessage() {}

func (x *GetAccountTypesReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTypesReq.ProtoReflect.Descriptor instead.
func (*GetAccountTypesReq) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{8}
}

type GetAccountTypesRes struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Types         map[int32]*base.AccountTypeConfig `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Base          *base.BaseResponse                `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTypesRes) Reset() {
	*x = GetAccountTypesRes{}
	mi := &file_config_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTypesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTypesRes) ProtoMessage() {}

func (x *GetAccountTypesRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTypesRes.ProtoReflect.Descriptor instead.
func (*GetAccountTypesRes) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *GetAccountTypesRes) GetTypes() map[int32]*base.AccountTypeConfig {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *GetAccountTypesRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_config_v1_config_proto protoreflect.FileDescriptor

const file_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16config/v1/config.proto\x12\tconfig.v1\x1a\x0fbase/base.proto\"\x13\n" +
	"\x11ListCurrenciesReq\"r\n" +
	"\x11ListCurrenciesRes\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\x12\x1e\n" +
	"\n" +
	"currencies\x18\x02 \x03(\tR\n" +
	"currencies\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"$\n" +
	"\x0eAddCurrencyReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"o\n" +
	"\x0eAddCurrencyRes\x12\x14\n" +
	"\x05codes\x18\x01 \x03(\tR\x05codes\x12\x1e\n" +
	"\n" +
	"currencies\x18\x02 \x03(\tR\n" +
	"currencies\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"'\n" +
	"\x11DeleteCurrencyReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"<\n" +
	"\x11DeleteCurrencyRes\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x0e\n" +
	"\fGetThemesReq\"\\\n" +
	"\fGetThemesRes\x12#\n" +
	"\x06themes\x18\x01 \x03(\v2\v.base.ThemeR\x06themes\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x14\n" +
	"\x12GetAccountTypesReq\"\xd0\x01\n" +
	"\x12GetAccountTypesRes\x12>\n" +
	"\x05types\x18\x01 \x03(\v2(.config.v1.GetAccountTypesRes.TypesEntryR\x05types\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\x1aQ\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.base.AccountTypeConfigR\x05value:\x028\x012\x80\x03\n" +
	"\rConfigService\x12L\n" +
	"\x0eListCurrencies\x12\x1c.config.v1.ListCurrenciesReq\x1a\x1c.config.v1.ListCurrenciesRes\x12C\n" +
	"\vAddCurrency\x12\x19.config.v1.AddCurrencyReq\x1a\x19.config.v1.AddCurrencyRes\x12L\n" +
	"\x0eDeleteCurrency\x12\x1c.config.v1.DeleteCurrencyReq\x1a\x1c.config.v1.DeleteCurrencyRes\x12=\n" +
	"\tGetThemes\x12\x17.config.v1.GetThemesReq\x1a\x17.config.v1.GetThemesRes\x12O\n" +
	"\x0fGetAccountTypes\x12\x1d.config.v1.GetAccountTypesReq\x1a\x1d.config.v1.GetAccountTypesResB\x1bZ\x19gaap-api/api/config/v1;v1b\x06proto3"

var (
	file_config_v1_config_proto_rawDescOnce sync.Once
	file_config_v1_config_proto_rawDescData []byte
)

func file_config_v1_config_proto_rawDescGZIP() []byte {
	file_config_v1_config_proto_rawDescOnce.Do(func() {
		file_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)))
	})
	return file_config_v1_config_proto_rawDescData
}

var file_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_config_v1_config_proto_goTypes = []any{
	(*ListCurrenciesReq)(nil),      // 0: config.v1.ListCurrenciesReq
	(*ListCurrenciesRes)(nil),      // 1: config.v1.ListCurrenciesRes
	(*AddCurrencyReq)(nil),         // 2: config.v1.AddCurrencyReq
	(*AddCurrencyRes)(nil),         // 3: config.v1.AddCurrencyRes
	(*DeleteCurrencyReq)(nil),      // 4: config.v1.DeleteCurrencyReq
	(*DeleteCurrencyRes)(nil),      // 5: config.v1.DeleteCurrencyRes
	(*GetThemesReq)(nil),           // 6: config.v1.GetThemesReq
	(*GetThemesRes)(nil),           // 7: config.v1.GetThemesRes
	(*GetAccountTypesReq)(nil),     // 8: config.v1.GetAccountTypesReq
	(*GetAccountTypesRes)(nil),     // 9: config.v1.GetAccountTypesRes
	nil,                            // 10: config.v1.GetAccountTypesRes.TypesEntry
	(*base.BaseResponse)(nil),      // 11: base.BaseResponse
	(*base.Theme)(nil),             // 12: base.Theme
	(*base.AccountTypeConfig)(nil), // 13: base.AccountTypeConfig
}
var file_config_v1_config_proto_depIdxs = []int32{
	11, // 0: config.v1.ListCurrenciesRes.base:type_name -> base.BaseResponse
	11, // 1: config.v1.AddCurrencyRes.base:type_name -> base.BaseResponse
	11, // 2: config.v1.DeleteCurrencyRes.base:type_name -> base.BaseResponse
	12, // 3: config.v1.GetThemesRes.themes:type_name -> base.Theme
	11, // 4: config.v1.GetThemesRes.base:type_name -> base.BaseResponse
	10, // 5: config.v1.GetAccountTypesRes.types:type_name -> config.v1.GetAccountTypesRes.TypesEntry
	11, // 6: config.v1.GetAccountTypesRes.base:type_name -> base.BaseResponse
	13, // 7: config.v1.GetAccountTypesRes.TypesEntry.value:type_name -> base.AccountTypeConfig
	0,  // 8: config.v1.ConfigService.ListCurrencies:input_type -> config.v1.ListCurrenciesReq
	2,  // 9: config.v1.ConfigService.AddCurrency:input_type -> config.v1.AddCurrencyReq
	4,  // 10: config.v1.ConfigService.DeleteCurrency:input_type -> config.v1.DeleteCurrencyReq
	6,  // 11: config.v1.ConfigService.GetThemes:input_type -> config.v1.GetThemesReq
	8,  // 12: config.v1.ConfigService.GetAccountTypes:input_type -> config.v1.GetAccountTypesReq
	1,  // 13: config.v1.ConfigService.ListCurrencies:output_type -> config.v1.ListCurrenciesRes
	3,  // 14: config.v1.ConfigService.AddCurrency:output_type -> config.v1.AddCurrencyRes
	5,  // 15: config.v1.ConfigService.DeleteCurrency:output_type -> config.v1.DeleteCurrencyRes
	7,  // 16: config.v1.ConfigService.GetThemes:output_type -> config.v1.GetThemesRes
	9,  // 17: config.v1.ConfigService.GetAccountTypes:output_type -> config.v1.GetAccountTypesRes
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_config_v1_config_proto_init() }
func file_config_v1_config_proto_init() {
	if File_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_config_proto_goTypes,
		DependencyIndexes: file_config_v1_config_proto_depIdxs,
		MessageInfos:      file_config_v1_config_proto_msgTypes,
	}.Build()
	File_config_v1_config_proto = out.File
	file_config_v1_config_proto_goTypes = nil
	file_config_v1_config_proto_depIdxs = nil
}
