// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: config/v1/config.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigService_ListCurrencies_FullMethodName  = "/config.v1.ConfigService/ListCurrencies"
	ConfigService_AddCurrency_FullMethodName     = "/config.v1.ConfigService/AddCurrency"
	ConfigService_DeleteCurrency_FullMethodName  = "/config.v1.ConfigService/DeleteCurrency"
	ConfigService_GetThemes_FullMethodName       = "/config.v1.ConfigService/GetThemes"
	ConfigService_GetAccountTypes_FullMethodName = "/config.v1.ConfigService/GetAccountTypes"
)

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	// Get supported currencies
	ListCurrencies(ctx context.Context, in *ListCurrenciesReq, opts ...grpc.CallOption) (*ListCurrenciesRes, error)
	// Add a supported currency
	AddCurrency(ctx context.Context, in *AddCurrencyReq, opts ...grpc.CallOption) (*AddCurrencyRes, error)
	// Remove a supported currency
	DeleteCurrency(ctx context.Context, in *DeleteCurrencyReq, opts ...grpc.CallOption) (*DeleteCurrencyRes, error)
	// Get available themes
	GetThemes(ctx context.Context, in *GetThemesReq, opts ...grpc.CallOption) (*GetThemesRes, error)
	// Get account type definitions
	GetAccountTypes(ctx context.Context, in *GetAccountTypesReq, opts ...grpc.CallOption) (*GetAccountTypesRes, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) ListCurrencies(ctx context.Context, in *ListCurrenciesReq, opts ...grpc.CallOption) (*ListCurrenciesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCurrenciesRes)
	err := c.cc.Invoke(ctx, ConfigService_ListCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) AddCurrency(ctx context.Context, in *AddCurrencyReq, opts ...grpc.CallOption) (*AddCurrencyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCurrencyRes)
	err := c.cc.Invoke(ctx, ConfigService_AddCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) DeleteCurrency(ctx context.Context, in *DeleteCurrencyReq, opts ...grpc.CallOption) (*DeleteCurrencyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCurrencyRes)
	err := c.cc.Invoke(ctx, ConfigService_DeleteCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetThemes(ctx context.Context, in *GetThemesReq, opts ...grpc.CallOption) (*GetThemesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThemesRes)
	err := c.cc.Invoke(ctx, ConfigService_GetThemes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) GetAccountTypes(ctx context.Context, in *GetAccountTypesReq, opts ...grpc.CallOption) (*GetAccountTypesRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountTypesRes)
	err := c.cc.Invoke(ctx, ConfigService_GetAccountTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility.
type ConfigServiceServer interface {
	// Get supported currencies
	ListCurrencies(context.Context, *ListCurrenciesReq) (*ListCurrenciesRes, error)
	// Add a supported currency
	AddCurrency(context.Context, *AddCurrencyReq) (*AddCurrencyRes, error)
	// Remove a supported currency
	DeleteCurrency(context.Context, *DeleteCurrencyReq) (*DeleteCurrencyRes, error)
	// Get available themes
	GetThemes(context.Context, *GetThemesReq) (*GetThemesRes, error)
	// Get account type definitions
	GetAccountTypes(context.Context, *GetAccountTypesReq) (*GetAccountTypesRes, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) ListCurrencies(context.Context, *ListCurrenciesReq) (*ListCurrenciesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCurrencies not implemented")
}
func (UnimplementedConfigServiceServer) AddCurrency(context.Context, *AddCurrencyReq) (*AddCurrencyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCurrency not implemented")
}
func (UnimplementedConfigServiceServer) DeleteCurrency(context.Context, *DeleteCurrencyReq) (*DeleteCurrencyRes, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCurrency not implemented")
}
func (UnimplementedConfigServiceServer) GetThemes(context.Context, *GetThemesReq) (*GetThemesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetThemes not implemented")
}
func (UnimplementedConfigServiceServer) GetAccountTypes(context.Context, *GetAccountTypesReq) (*GetAccountTypesRes, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountTypes not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_ListCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCurrenciesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ListCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_ListCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ListCurrencies(ctx, req.(*ListCurrenciesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_AddCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCurrencyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).AddCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_AddCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).AddCurrency(ctx, req.(*AddCurrencyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_DeleteCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCurrencyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).DeleteCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_DeleteCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).DeleteCurrency(ctx, req.(*DeleteCurrencyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetThemes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThemesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetThemes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetThemes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetThemes(ctx, req.(*GetThemesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_GetAccountTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountTypesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).GetAccountTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_GetAccountTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).GetAccountTypes(ctx, req.(*GetAccountTypesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "config.v1.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCurrencies",
			Handler:    _ConfigService_ListCurrencies_Handler,
		},
		{
			MethodName: "AddCurrency",
			Handler:    _ConfigService_AddCurrency_Handler,
		},
		{
			MethodName: "DeleteCurrency",
			Handler:    _ConfigService_DeleteCurrency_Handler,
		},
		{
			MethodName: "GetThemes",
			Handler:    _ConfigService_GetThemes_Handler,
		},
		{
			MethodName: "GetAccountTypes",
			Handler:    _ConfigService_GetAccountTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config/v1/config.proto",
}
