// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package transaction

import (
	"context"

	"gaap-api/api/base"
	v1 "gaap-api/api/transaction/v1"
	"gaap-api/internal/middleware"
	"gaap-api/internal/model"
	"gaap-api/internal/model/entity"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// =============================================================================
// Helper functions for PB <-> Entity conversion
// =============================================================================

// requireUserIdFromContext extracts user ID from context, panics if not found
func requireUserIdFromContext(ctx context.Context) uuid.UUID {
	id, ok := ctx.Value(middleware.UserIdKey).(string)
	if !ok || id == "" {
		g.Log().Panicf(ctx, "user id not found in context")
	}
	parsedId, err := uuid.Parse(id)
	if err != nil {
		g.Log().Panicf(ctx, "invalid user id format: %s", id)
	}
	return parsedId
}

// gtimeToDateString safely converts *gtime.Time to date string (YYYY-MM-DD)
func gtimeToDateString(t *gtime.Time) string {
	if t == nil {
		return ""
	}
	return t.Format("Y-m-d")
}

// entityToProto converts entity.Transactions to protobuf v1.Transaction
func entityToProto(e *entity.Transactions) *v1.Transaction {
	if e == nil {
		return nil
	}

	tx := &v1.Transaction{
		Id:   e.Id.String(),
		Date: gtimeToDateString(e.Date),
		From: e.FromAccountId.String(),
		To:   e.ToAccountId.String(),
		Note: e.Note,
		Type: base.TransactionType(e.Type),
		Amount: &base.Money{
			CurrencyCode: e.CurrencyCode,
			Units:        e.BalanceUnits,
			Nanos:        int32(e.BalanceNanos),
		},
	}

	if e.CreatedAt != nil {
		tx.CreatedAt = timestamppb.New(e.CreatedAt.Time)
	}
	if e.UpdatedAt != nil {
		tx.UpdatedAt = timestamppb.New(e.UpdatedAt.Time)
	}

	return tx
}

// entitiesToProtos converts a slice of entity.Transactions to protobuf v1.Transaction slice
func entitiesToProtos(entities []entity.Transactions) []*v1.Transaction {
	result := make([]*v1.Transaction, len(entities))
	for i := range entities {
		result[i] = entityToProto(&entities[i])
	}
	return result
}

// protoInputToCreateInput converts protobuf TransactionInput to model.TransactionCreateInput
func protoInputToCreateInput(ctx context.Context, input *v1.TransactionInput) model.TransactionCreateInput {
	result := model.TransactionCreateInput{
		UserId: requireUserIdFromContext(ctx),
		Date:   input.GetDate(),
		Note:   input.GetNote(),
		Type:   int(input.GetType()),
	}

	// Handle from account ID
	if input.GetFrom() != "" {
		if fromId, err := uuid.Parse(input.GetFrom()); err == nil {
			result.FromAccountId = fromId
		}
	}

	// Handle to account ID
	if input.GetTo() != "" {
		if toId, err := uuid.Parse(input.GetTo()); err == nil {
			result.ToAccountId = toId
		}
	}

	// Handle amount (Money type)
	if input.GetAmount() != nil {
		result.CurrencyCode = input.GetAmount().GetCurrencyCode()
		result.BalanceUnits = input.GetAmount().GetUnits()
		result.BalanceNanos = int(input.GetAmount().GetNanos())
	}

	return result
}

// protoInputToUpdateInput converts protobuf TransactionInput to model.TransactionUpdateInput
func protoInputToUpdateInput(input *v1.TransactionInput) model.TransactionUpdateInput {
	result := model.TransactionUpdateInput{
		Date: input.GetDate(),
		Note: input.GetNote(),
		Type: int(input.GetType()),
	}

	// Handle from account ID
	if input.GetFrom() != "" {
		if fromId, err := uuid.Parse(input.GetFrom()); err == nil {
			result.FromAccountId = fromId
		}
	}

	// Handle to account ID
	if input.GetTo() != "" {
		if toId, err := uuid.Parse(input.GetTo()); err == nil {
			result.ToAccountId = toId
		}
	}

	// Handle amount (Money type)
	if input.GetAmount() != nil {
		result.CurrencyCode = input.GetAmount().GetCurrencyCode()
		result.BalanceUnits = input.GetAmount().GetUnits()
		result.BalanceNanos = int(input.GetAmount().GetNanos())
	}

	return result
}

// protoQueryToInput converts protobuf TransactionQuery to model.TransactionQueryInput
func protoQueryToInput(query *v1.TransactionQuery) model.TransactionQueryInput {
	if query == nil {
		return model.TransactionQueryInput{
			Page:  1,
			Limit: 20,
		}
	}

	result := model.TransactionQueryInput{
		Page:      int(query.GetPage()),
		Limit:     int(query.GetLimit()),
		StartDate: query.GetStartDate(),
		EndDate:   query.GetEndDate(),
		Type:      int(query.GetType()),
		SortBy:    query.GetSortBy(),
		SortOrder: query.GetSortOrder(),
	}

	// Handle optional account_id
	if query.GetAccountId() != "" {
		if accountId, err := uuid.Parse(query.GetAccountId()); err == nil {
			result.AccountId = accountId
		}
	}

	// Set defaults
	if result.Page <= 0 {
		result.Page = 1
	}
	if result.Limit <= 0 {
		result.Limit = 20
	}

	return result
}
