// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// accountTypesDao is the data access object for the table account_types.
// You can define custom methods on it to extend its functionality as needed.
type accountTypesDao struct {
	*internal.AccountTypesDao
}

var (
	// AccountTypes is a globally accessible object for table account_types operations.
	AccountTypes = accountTypesDao{internal.NewAccountTypesDao()}
)

// Add your custom methods and functionality below.
