// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// accountsDao is the data access object for the table accounts.
// You can define custom methods on it to extend its functionality as needed.
type accountsDao struct {
	*internal.AccountsDao
}

var (
	// Accounts is a globally accessible object for table accounts operations.
	Accounts = accountsDao{internal.NewAccountsDao()}
)

// Add your custom methods and functionality below.
