// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// currenciesDao is the data access object for the table currencies.
// You can define custom methods on it to extend its functionality as needed.
type currenciesDao struct {
	*internal.CurrenciesDao
}

var (
	// Currencies is a globally accessible object for table currencies operations.
	Currencies = currenciesDao{internal.NewCurrenciesDao()}
)

// Add your custom methods and functionality below.
