// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// dashboardSnapshotsDao is the data access object for the table dashboard_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type dashboardSnapshotsDao struct {
	*internal.DashboardSnapshotsDao
}

var (
	// DashboardSnapshots is a globally accessible object for table dashboard_snapshots operations.
	DashboardSnapshots = dashboardSnapshotsDao{internal.NewDashboardSnapshotsDao()}
)

// Add your custom methods and functionality below.
