// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// demoUserBaselinesDao is the data access object for the table demo_user_baselines.
// You can define custom methods on it to extend its functionality as needed.
type demoUserBaselinesDao struct {
	*internal.DemoUserBaselinesDao
}

var (
	// DemoUserBaselines is a globally accessible object for table demo_user_baselines operations.
	DemoUserBaselines = demoUserBaselinesDao{internal.NewDemoUserBaselinesDao()}
)

// Add your custom methods and functionality below.
