// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// migrationMappingsDao is the data access object for the table migration_mappings.
type migrationMappingsDao struct {
	*internal.MigrationMappingsDao
}

var (
	// MigrationMappings is a globally accessible object for table migration_mappings operations.
	MigrationMappings = migrationMappingsDao{internal.NewMigrationMappingsDao()}
)
