// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// oauthConnectionsDao is the data access object for the table oauth_connections.
// You can define custom methods on it to extend its functionality as needed.
type oauthConnectionsDao struct {
	*internal.OauthConnectionsDao
}

var (
	// OauthConnections is a globally accessible object for table oauth_connections operations.
	OauthConnections = oauthConnectionsDao{internal.NewOauthConnectionsDao()}
)

// Add your custom methods and functionality below.
