// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// tasksDao is the data access object for the table tasks.
type tasksDao struct {
	*internal.TasksDao
}

var (
	// Tasks is a globally accessible object for table tasks operations.
	Tasks = tasksDao{internal.NewTasksDao()}
)
