// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gaap-api/internal/dao/internal"
)

// themesDao is the data access object for the table themes.
// You can define custom methods on it to extend its functionality as needed.
type themesDao struct {
	*internal.ThemesDao
}

var (
	// Themes is a globally accessible object for table themes operations.
	Themes = themesDao{internal.NewThemesDao()}
)

// Add your custom methods and functionality below.
