// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package data

import (
	v1 "gaap-api/api/data/v1"
)

// taskToProto is a placeholder for task conversion (will be handled by task controller)
var _ = v1.ExportDataRes{}
