// Code generated by genctrl. DO NOT EDIT.
// Source: task/v1/task.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for TaskService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfListTasksReq is the GoFrame-compatible request wrapper for ListTasks
type GfListTasksReq struct {
	g.Meta `path:"/v1/task/list-tasks" method:"POST" tags:"task" summary:"List all tasks"`
	ListTasksReq
}

// GfListTasksRes is the GoFrame-compatible response wrapper for ListTasks
type GfListTasksRes = ListTasksRes


// GfGetTaskReq is the GoFrame-compatible request wrapper for GetTask
type GfGetTaskReq struct {
	g.Meta `path:"/v1/task/get-task" method:"POST" tags:"task" summary:"Get task details"`
	GetTaskReq
}

// GfGetTaskRes is the GoFrame-compatible response wrapper for GetTask
type GfGetTaskRes = GetTaskRes


// GfCancelTaskReq is the GoFrame-compatible request wrapper for CancelTask
type GfCancelTaskReq struct {
	g.Meta `path:"/v1/task/cancel-task" method:"POST" tags:"task" summary:"Cancel a task"`
	CancelTaskReq
}

// GfCancelTaskRes is the GoFrame-compatible response wrapper for CancelTask
type GfCancelTaskRes = CancelTaskRes


// GfRetryTaskReq is the GoFrame-compatible request wrapper for RetryTask
type GfRetryTaskReq struct {
	g.Meta `path:"/v1/task/retry-task" method:"POST" tags:"task" summary:"Retry a task"`
	RetryTaskReq
}

// GfRetryTaskRes is the GoFrame-compatible response wrapper for RetryTask
type GfRetryTaskRes = RetryTaskRes


