// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: task/v1/task.proto

package v1

import (
	base "gaap-api/api/base"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_TASK_TYPE_UNSPECIFIED       TaskType = 0 // Default
	TaskType_TASK_TYPE_ACCOUNT_MIGRATION TaskType = 1
	TaskType_TASK_TYPE_EXPORT_DATA       TaskType = 2
	TaskType_TASK_TYPE_IMPORT_DATA       TaskType = 3
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TASK_TYPE_UNSPECIFIED",
		1: "TASK_TYPE_ACCOUNT_MIGRATION",
		2: "TASK_TYPE_EXPORT_DATA",
		3: "TASK_TYPE_IMPORT_DATA",
	}
	TaskType_value = map[string]int32{
		"TASK_TYPE_UNSPECIFIED":       0,
		"TASK_TYPE_ACCOUNT_MIGRATION": 1,
		"TASK_TYPE_EXPORT_DATA":       2,
		"TASK_TYPE_IMPORT_DATA":       3,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_task_v1_task_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{0}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0 // Default
	TaskStatus_TASK_STATUS_PENDING     TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING     TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED   TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED      TaskStatus = 4
	TaskStatus_TASK_STATUS_CANCELLED   TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_PENDING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_PENDING":     1,
		"TASK_STATUS_RUNNING":     2,
		"TASK_STATUS_COMPLETED":   3,
		"TASK_STATUS_FAILED":      4,
		"TASK_STATUS_CANCELLED":   5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_v1_task_proto_enumTypes[1].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_v1_task_proto_enumTypes[1]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{1}
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           TaskType               `protobuf:"varint,2,opt,name=type,proto3,enum=task.v1.TaskType" json:"type,omitempty"`
	Status         TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=task.v1.TaskStatus" json:"status,omitempty"`
	Payload        *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Result         *structpb.Struct       `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Progress       int32                  `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	TotalItems     int32                  `protobuf:"varint,7,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	ProcessedItems int32                  `protobuf:"varint,8,opt,name=processed_items,json=processedItems,proto3" json:"processed_items,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Task) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Task) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Task) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *Task) GetProcessedItems() int32 {
	if x != nil {
		return x.ProcessedItems
	}
	return 0
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TaskQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        TaskStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=task.v1.TaskStatus" json:"status,omitempty"`
	Type          TaskType               `protobuf:"varint,4,opt,name=type,proto3,enum=task.v1.TaskType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskQuery) Reset() {
	*x = TaskQuery{}
	mi := &file_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskQuery) ProtoMessage() {}

func (x *TaskQuery) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskQuery.ProtoReflect.Descriptor instead.
func (*TaskQuery) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskQuery) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TaskQuery) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TaskQuery) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *TaskQuery) GetType() TaskType {
	if x != nil {
		return x.Type
	}
	return TaskType_TASK_TYPE_UNSPECIFIED
}

type ListTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *TaskQuery             `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReq) Reset() {
	*x = ListTasksReq{}
	mi := &file_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReq) ProtoMessage() {}

func (x *ListTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReq.ProtoReflect.Descriptor instead.
func (*ListTasksReq) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *ListTasksReq) GetQuery() *TaskQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListTasksRes struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          []*Task                 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *base.PaginatedResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Base          *base.BaseResponse      `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRes) Reset() {
	*x = ListTasksRes{}
	mi := &file_task_v1_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRes) ProtoMessage() {}

func (x *ListTasksRes) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRes.ProtoReflect.Descriptor instead.
func (*ListTasksRes) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{3}
}

func (x *ListTasksRes) GetData() []*Task {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListTasksRes) GetPagination() *base.PaginatedResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListTasksRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	mi := &file_task_v1_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRes) Reset() {
	*x = GetTaskRes{}
	mi := &file_task_v1_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRes) ProtoMessage() {}

func (x *GetTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRes.ProtoReflect.Descriptor instead.
func (*GetTaskRes) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskRes) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *GetTaskRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type CancelTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskReq) Reset() {
	*x = CancelTaskReq{}
	mi := &file_task_v1_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskReq) ProtoMessage() {}

func (x *CancelTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskReq.ProtoReflect.Descriptor instead.
func (*CancelTaskReq) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{6}
}

func (x *CancelTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRes) Reset() {
	*x = CancelTaskRes{}
	mi := &file_task_v1_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRes) ProtoMessage() {}

func (x *CancelTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRes.ProtoReflect.Descriptor instead.
func (*CancelTaskRes) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTaskRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type RetryTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskReq) Reset() {
	*x = RetryTaskReq{}
	mi := &file_task_v1_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskReq) ProtoMessage() {}

func (x *RetryTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskReq.ProtoReflect.Descriptor instead.
func (*RetryTaskReq) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{8}
}

func (x *RetryTaskReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetryTaskRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskRes) Reset() {
	*x = RetryTaskRes{}
	mi := &file_task_v1_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskRes) ProtoMessage() {}

func (x *RetryTaskRes) ProtoReflect() protoreflect.Message {
	mi := &file_task_v1_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskRes.ProtoReflect.Descriptor instead.
func (*RetryTaskRes) Descriptor() ([]byte, []int) {
	return file_task_v1_task_proto_rawDescGZIP(), []int{9}
}

func (x *RetryTaskRes) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *RetryTaskRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_task_v1_task_proto protoreflect.FileDescriptor

const file_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x12task/v1/task.proto\x12\atask.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0fbase/base.proto\"\xa4\x04\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.task.v1.TaskTypeR\x04type\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.task.v1.TaskStatusR\x06status\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x12/\n" +
	"\x06result\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x05R\bprogress\x12\x1f\n" +
	"\vtotal_items\x18\a \x01(\x05R\n" +
	"totalItems\x12'\n" +
	"\x0fprocessed_items\x18\b \x01(\x05R\x0eprocessedItems\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x89\x01\n" +
	"\tTaskQuery\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.task.v1.TaskStatusR\x06status\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.task.v1.TaskTypeR\x04type\"8\n" +
	"\fListTasksReq\x12(\n" +
	"\x05query\x18\x01 \x01(\v2\x12.task.v1.TaskQueryR\x05query\"\x93\x01\n" +
	"\fListTasksRes\x12!\n" +
	"\x04data\x18\x01 \x03(\v2\r.task.v1.TaskR\x04data\x127\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x17.base.PaginatedResponseR\n" +
	"pagination\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x1c\n" +
	"\n" +
	"GetTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\n" +
	"GetTaskRes\x12!\n" +
	"\x04task\x18\x01 \x01(\v2\r.task.v1.TaskR\x04task\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x1f\n" +
	"\rCancelTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\rCancelTaskRes\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x1e\n" +
	"\fRetryTaskReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\fRetryTaskRes\x12!\n" +
	"\x04task\x18\x01 \x01(\v2\r.task.v1.TaskR\x04task\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base*|\n" +
	"\bTaskType\x12\x19\n" +
	"\x15TASK_TYPE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTASK_TYPE_ACCOUNT_MIGRATION\x10\x01\x12\x19\n" +
	"\x15TASK_TYPE_EXPORT_DATA\x10\x02\x12\x19\n" +
	"\x15TASK_TYPE_IMPORT_DATA\x10\x03*\xa9\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x052\xf6\x01\n" +
	"\vTaskService\x129\n" +
	"\tListTasks\x12\x15.task.v1.ListTasksReq\x1a\x15.task.v1.ListTasksRes\x123\n" +
	"\aGetTask\x12\x13.task.v1.GetTaskReq\x1a\x13.task.v1.GetTaskRes\x12<\n" +
	"\n" +
	"CancelTask\x12\x16.task.v1.CancelTaskReq\x1a\x16.task.v1.CancelTaskRes\x129\n" +
	"\tRetryTask\x12\x15.task.v1.RetryTaskReq\x1a\x15.task.v1.RetryTaskResB\x19Z\x17gaap-api/api/task/v1;v1b\x06proto3"

var (
	file_task_v1_task_proto_rawDescOnce sync.Once
	file_task_v1_task_proto_rawDescData []byte
)

func file_task_v1_task_proto_rawDescGZIP() []byte {
	file_task_v1_task_proto_rawDescOnce.Do(func() {
		file_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_v1_task_proto_rawDesc), len(file_task_v1_task_proto_rawDesc)))
	})
	return file_task_v1_task_proto_rawDescData
}

var file_task_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_task_v1_task_proto_goTypes = []any{
	(TaskType)(0),                  // 0: task.v1.TaskType
	(TaskStatus)(0),                // 1: task.v1.TaskStatus
	(*Task)(nil),                   // 2: task.v1.Task
	(*TaskQuery)(nil),              // 3: task.v1.TaskQuery
	(*ListTasksReq)(nil),           // 4: task.v1.ListTasksReq
	(*ListTasksRes)(nil),           // 5: task.v1.ListTasksRes
	(*GetTaskReq)(nil),             // 6: task.v1.GetTaskReq
	(*GetTaskRes)(nil),             // 7: task.v1.GetTaskRes
	(*CancelTaskReq)(nil),          // 8: task.v1.CancelTaskReq
	(*CancelTaskRes)(nil),          // 9: task.v1.CancelTaskRes
	(*RetryTaskReq)(nil),           // 10: task.v1.RetryTaskReq
	(*RetryTaskRes)(nil),           // 11: task.v1.RetryTaskRes
	(*structpb.Struct)(nil),        // 12: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
	(*base.PaginatedResponse)(nil), // 14: base.PaginatedResponse
	(*base.BaseResponse)(nil),      // 15: base.BaseResponse
}
var file_task_v1_task_proto_depIdxs = []int32{
	0,  // 0: task.v1.Task.type:type_name -> task.v1.TaskType
	1,  // 1: task.v1.Task.status:type_name -> task.v1.TaskStatus
	12, // 2: task.v1.Task.payload:type_name -> google.protobuf.Struct
	12, // 3: task.v1.Task.result:type_name -> google.protobuf.Struct
	13, // 4: task.v1.Task.started_at:type_name -> google.protobuf.Timestamp
	13, // 5: task.v1.Task.completed_at:type_name -> google.protobuf.Timestamp
	13, // 6: task.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	13, // 7: task.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: task.v1.TaskQuery.status:type_name -> task.v1.TaskStatus
	0,  // 9: task.v1.TaskQuery.type:type_name -> task.v1.TaskType
	3,  // 10: task.v1.ListTasksReq.query:type_name -> task.v1.TaskQuery
	2,  // 11: task.v1.ListTasksRes.data:type_name -> task.v1.Task
	14, // 12: task.v1.ListTasksRes.pagination:type_name -> base.PaginatedResponse
	15, // 13: task.v1.ListTasksRes.base:type_name -> base.BaseResponse
	2,  // 14: task.v1.GetTaskRes.task:type_name -> task.v1.Task
	15, // 15: task.v1.GetTaskRes.base:type_name -> base.BaseResponse
	15, // 16: task.v1.CancelTaskRes.base:type_name -> base.BaseResponse
	2,  // 17: task.v1.RetryTaskRes.task:type_name -> task.v1.Task
	15, // 18: task.v1.RetryTaskRes.base:type_name -> base.BaseResponse
	4,  // 19: task.v1.TaskService.ListTasks:input_type -> task.v1.ListTasksReq
	6,  // 20: task.v1.TaskService.GetTask:input_type -> task.v1.GetTaskReq
	8,  // 21: task.v1.TaskService.CancelTask:input_type -> task.v1.CancelTaskReq
	10, // 22: task.v1.TaskService.RetryTask:input_type -> task.v1.RetryTaskReq
	5,  // 23: task.v1.TaskService.ListTasks:output_type -> task.v1.ListTasksRes
	7,  // 24: task.v1.TaskService.GetTask:output_type -> task.v1.GetTaskRes
	9,  // 25: task.v1.TaskService.CancelTask:output_type -> task.v1.CancelTaskRes
	11, // 26: task.v1.TaskService.RetryTask:output_type -> task.v1.RetryTaskRes
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_task_v1_task_proto_init() }
func file_task_v1_task_proto_init() {
	if File_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_v1_task_proto_rawDesc), len(file_task_v1_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_v1_task_proto_goTypes,
		DependencyIndexes: file_task_v1_task_proto_depIdxs,
		EnumInfos:         file_task_v1_task_proto_enumTypes,
		MessageInfos:      file_task_v1_task_proto_msgTypes,
	}.Build()
	File_task_v1_task_proto = out.File
	file_task_v1_task_proto_goTypes = nil
	file_task_v1_task_proto_depIdxs = nil
}
