// Code generated by genctrl. DO NOT EDIT.
// Source: health/v1/health.proto

package v1

import (
	"github.com/gogf/gf/v2/frame/g"
)

// =============================================================================
// GoFrame API Wrappers for HealthService
// These wrapper types add g.Meta annotations to enable gf gen ctrl compatibility
// The wrapper types embed the original Protobuf types with a "Gf" prefix
// =============================================================================


// GfHealthReq is the GoFrame-compatible request wrapper for Health
type GfHealthReq struct {
	g.Meta `path:"/health/health" method:"POST" tags:"health" summary:"Health check"`
	*HealthReq
}

// GfHealthRes is the GoFrame-compatible response wrapper for Health
type GfHealthRes = HealthRes


