// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: auth/v1/auth.proto

package v1

import (
	base "gaap-api/api/base"
	v1 "gaap-api/api/user/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePasswordReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Password        string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdatePasswordReq) Reset() {
	*x = UpdatePasswordReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReq) ProtoMessage() {}

func (x *UpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdatePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *UpdatePasswordReq) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type UpdatePasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRes) Reset() {
	*x = UpdatePasswordRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRes) ProtoMessage() {}

func (x *UpdatePasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRes.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePasswordRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	User          *v1.User               `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	SessionKey    string                 `protobuf:"bytes,4,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty" dc:"ALE session key (hex encoded)"` // ALE session key (hex encoded)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResponse) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

type LoginReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Email               string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password            string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Code                string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CfTurnstileResponse string                 `protobuf:"bytes,4,opt,name=cf_turnstile_response,json=cfTurnstileResponse,proto3" json:"cf_turnstile_response,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginReq) GetCfTurnstileResponse() string {
	if x != nil {
		return x.CfTurnstileResponse
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *AuthResponse          `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginRes) GetAuth() *AuthResponse {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *LoginRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type DemoLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoLoginReq) Reset() {
	*x = DemoLoginReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoLoginReq) ProtoMessage() {}

func (x *DemoLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoLoginReq.ProtoReflect.Descriptor instead.
func (*DemoLoginReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

type RegisterReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Email               string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password            string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname            string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	CfTurnstileResponse string                 `protobuf:"bytes,4,opt,name=cf_turnstile_response,json=cfTurnstileResponse,proto3" json:"cf_turnstile_response,omitempty"`
	MainCurrency        string                 `protobuf:"bytes,5,opt,name=main_currency,json=mainCurrency,proto3" json:"main_currency,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterReq) GetCfTurnstileResponse() string {
	if x != nil {
		return x.CfTurnstileResponse
	}
	return ""
}

func (x *RegisterReq) GetMainCurrency() string {
	if x != nil {
		return x.MainCurrency
	}
	return ""
}

type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *AuthResponse          `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterRes) GetAuth() *AuthResponse {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *RegisterRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

type LogoutRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRes) Reset() {
	*x = LogoutRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRes) ProtoMessage() {}

func (x *LogoutRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRes.ProtoReflect.Descriptor instead.
func (*LogoutRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	SessionKey    string                 `protobuf:"bytes,3,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty" dc:"ALE session key (hex encoded)"` // ALE session key (hex encoded)
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRes) Reset() {
	*x = RefreshTokenRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRes) ProtoMessage() {}

func (x *RefreshTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRes.ProtoReflect.Descriptor instead.
func (*RefreshTokenRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenRes) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRes) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *RefreshTokenRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type TwoFactorSecret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoFactorSecret) Reset() {
	*x = TwoFactorSecret{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoFactorSecret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoFactorSecret) ProtoMessage() {}

func (x *TwoFactorSecret) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoFactorSecret.ProtoReflect.Descriptor instead.
func (*TwoFactorSecret) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *TwoFactorSecret) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *TwoFactorSecret) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Generate2FAReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generate2FAReq) Reset() {
	*x = Generate2FAReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generate2FAReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generate2FAReq) ProtoMessage() {}

func (x *Generate2FAReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generate2FAReq.ProtoReflect.Descriptor instead.
func (*Generate2FAReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

type Generate2FARes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *TwoFactorSecret       `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generate2FARes) Reset() {
	*x = Generate2FARes{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generate2FARes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generate2FARes) ProtoMessage() {}

func (x *Generate2FARes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generate2FARes.ProtoReflect.Descriptor instead.
func (*Generate2FARes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *Generate2FARes) GetSecret() *TwoFactorSecret {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *Generate2FARes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type Enable2FAReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enable2FAReq) Reset() {
	*x = Enable2FAReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enable2FAReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enable2FAReq) ProtoMessage() {}

func (x *Enable2FAReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enable2FAReq.ProtoReflect.Descriptor instead.
func (*Enable2FAReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *Enable2FAReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Enable2FARes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enable2FARes) Reset() {
	*x = Enable2FARes{}
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enable2FARes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enable2FARes) ProtoMessage() {}

func (x *Enable2FARes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enable2FARes.ProtoReflect.Descriptor instead.
func (*Enable2FARes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *Enable2FARes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type Disable2FAReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable2FAReq) Reset() {
	*x = Disable2FAReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable2FAReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable2FAReq) ProtoMessage() {}

func (x *Disable2FAReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable2FAReq.ProtoReflect.Descriptor instead.
func (*Disable2FAReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *Disable2FAReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Disable2FAReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Disable2FARes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disable2FARes) Reset() {
	*x = Disable2FARes{}
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disable2FARes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disable2FARes) ProtoMessage() {}

func (x *Disable2FARes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disable2FARes.ProtoReflect.Descriptor instead.
func (*Disable2FARes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *Disable2FARes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type CurrencyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyInfo) Reset() {
	*x = CurrencyInfo{}
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyInfo) ProtoMessage() {}

func (x *CurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyInfo.ProtoReflect.Descriptor instead.
func (*CurrencyInfo) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *CurrencyInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetCurrencyListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyListReq) Reset() {
	*x = GetCurrencyListReq{}
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyListReq) ProtoMessage() {}

func (x *GetCurrencyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyListReq.ProtoReflect.Descriptor instead.
func (*GetCurrencyListReq) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{20}
}

type GetCurrencyListRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*CurrencyInfo        `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	Base          *base.BaseResponse     `protobuf:"bytes,255,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyListRes) Reset() {
	*x = GetCurrencyListRes{}
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyListRes) ProtoMessage() {}

func (x *GetCurrencyListRes) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyListRes.ProtoReflect.Descriptor instead.
func (*GetCurrencyListRes) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *GetCurrencyListRes) GetCurrencies() []*CurrencyInfo {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *GetCurrencyListRes) GetBase() *base.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x0fbase/base.proto\x1a\x12user/v1/user.proto\"}\n" +
	"\x11UpdatePasswordReq\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12)\n" +
	"\x10confirm_password\x18\x03 \x01(\tR\x0fconfirmPassword\"<\n" +
	"\x11UpdatePasswordRes\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x9a\x01\n" +
	"\fAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12!\n" +
	"\x04user\x18\x03 \x01(\v2\r.user.v1.UserR\x04user\x12\x1f\n" +
	"\vsession_key\x18\x04 \x01(\tR\n" +
	"sessionKey\"\x84\x01\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x122\n" +
	"\x15cf_turnstile_response\x18\x04 \x01(\tR\x13cfTurnstileResponse\"^\n" +
	"\bLoginRes\x12)\n" +
	"\x04auth\x18\x01 \x01(\v2\x15.auth.v1.AuthResponseR\x04auth\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\x0e\n" +
	"\fDemoLoginReq\"\xb4\x01\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x122\n" +
	"\x15cf_turnstile_response\x18\x04 \x01(\tR\x13cfTurnstileResponse\x12#\n" +
	"\rmain_currency\x18\x05 \x01(\tR\fmainCurrency\"a\n" +
	"\vRegisterRes\x12)\n" +
	"\x04auth\x18\x01 \x01(\v2\x15.auth.v1.AuthResponseR\x04auth\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\v\n" +
	"\tLogoutReq\"4\n" +
	"\tLogoutRes\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"6\n" +
	"\x0fRefreshTokenReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xa3\x01\n" +
	"\x0fRefreshTokenRes\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1f\n" +
	"\vsession_key\x18\x03 \x01(\tR\n" +
	"sessionKey\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\";\n" +
	"\x0fTwoFactorSecret\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x10\n" +
	"\x0eGenerate2FAReq\"k\n" +
	"\x0eGenerate2FARes\x120\n" +
	"\x06secret\x18\x01 \x01(\v2\x18.auth.v1.TwoFactorSecretR\x06secret\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\"\n" +
	"\fEnable2FAReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"7\n" +
	"\fEnable2FARes\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"?\n" +
	"\rDisable2FAReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"8\n" +
	"\rDisable2FARes\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base\"\"\n" +
	"\fCurrencyInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x14\n" +
	"\x12GetCurrencyListReq\"t\n" +
	"\x12GetCurrencyListRes\x125\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x15.auth.v1.CurrencyInfoR\n" +
	"currencies\x12'\n" +
	"\x04base\x18\xff\x01 \x01(\v2\x12.base.BaseResponseR\x04base2\xf2\x04\n" +
	"\vAuthService\x12-\n" +
	"\x05Login\x12\x11.auth.v1.LoginReq\x1a\x11.auth.v1.LoginRes\x125\n" +
	"\tDemoLogin\x12\x15.auth.v1.DemoLoginReq\x1a\x11.auth.v1.LoginRes\x126\n" +
	"\bRegister\x12\x14.auth.v1.RegisterReq\x1a\x14.auth.v1.RegisterRes\x120\n" +
	"\x06Logout\x12\x12.auth.v1.LogoutReq\x1a\x12.auth.v1.LogoutRes\x12B\n" +
	"\fRefreshToken\x12\x18.auth.v1.RefreshTokenReq\x1a\x18.auth.v1.RefreshTokenRes\x12?\n" +
	"\vGenerate2FA\x12\x17.auth.v1.Generate2FAReq\x1a\x17.auth.v1.Generate2FARes\x129\n" +
	"\tEnable2FA\x12\x15.auth.v1.Enable2FAReq\x1a\x15.auth.v1.Enable2FARes\x12<\n" +
	"\n" +
	"Disable2FA\x12\x16.auth.v1.Disable2FAReq\x1a\x16.auth.v1.Disable2FARes\x12H\n" +
	"\x0eUpdatePassword\x12\x1a.auth.v1.UpdatePasswordReq\x1a\x1a.auth.v1.UpdatePasswordRes\x12K\n" +
	"\x0fGetCurrencyList\x12\x1b.auth.v1.GetCurrencyListReq\x1a\x1b.auth.v1.GetCurrencyListResB\x19Z\x17gaap-api/api/auth/v1;v1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_auth_v1_auth_proto_goTypes = []any{
	(*UpdatePasswordReq)(nil),  // 0: auth.v1.UpdatePasswordReq
	(*UpdatePasswordRes)(nil),  // 1: auth.v1.UpdatePasswordRes
	(*AuthResponse)(nil),       // 2: auth.v1.AuthResponse
	(*LoginReq)(nil),           // 3: auth.v1.LoginReq
	(*LoginRes)(nil),           // 4: auth.v1.LoginRes
	(*DemoLoginReq)(nil),       // 5: auth.v1.DemoLoginReq
	(*RegisterReq)(nil),        // 6: auth.v1.RegisterReq
	(*RegisterRes)(nil),        // 7: auth.v1.RegisterRes
	(*LogoutReq)(nil),          // 8: auth.v1.LogoutReq
	(*LogoutRes)(nil),          // 9: auth.v1.LogoutRes
	(*RefreshTokenReq)(nil),    // 10: auth.v1.RefreshTokenReq
	(*RefreshTokenRes)(nil),    // 11: auth.v1.RefreshTokenRes
	(*TwoFactorSecret)(nil),    // 12: auth.v1.TwoFactorSecret
	(*Generate2FAReq)(nil),     // 13: auth.v1.Generate2FAReq
	(*Generate2FARes)(nil),     // 14: auth.v1.Generate2FARes
	(*Enable2FAReq)(nil),       // 15: auth.v1.Enable2FAReq
	(*Enable2FARes)(nil),       // 16: auth.v1.Enable2FARes
	(*Disable2FAReq)(nil),      // 17: auth.v1.Disable2FAReq
	(*Disable2FARes)(nil),      // 18: auth.v1.Disable2FARes
	(*CurrencyInfo)(nil),       // 19: auth.v1.CurrencyInfo
	(*GetCurrencyListReq)(nil), // 20: auth.v1.GetCurrencyListReq
	(*GetCurrencyListRes)(nil), // 21: auth.v1.GetCurrencyListRes
	(*base.BaseResponse)(nil),  // 22: base.BaseResponse
	(*v1.User)(nil),            // 23: user.v1.User
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	22, // 0: auth.v1.UpdatePasswordRes.base:type_name -> base.BaseResponse
	23, // 1: auth.v1.AuthResponse.user:type_name -> user.v1.User
	2,  // 2: auth.v1.LoginRes.auth:type_name -> auth.v1.AuthResponse
	22, // 3: auth.v1.LoginRes.base:type_name -> base.BaseResponse
	2,  // 4: auth.v1.RegisterRes.auth:type_name -> auth.v1.AuthResponse
	22, // 5: auth.v1.RegisterRes.base:type_name -> base.BaseResponse
	22, // 6: auth.v1.LogoutRes.base:type_name -> base.BaseResponse
	22, // 7: auth.v1.RefreshTokenRes.base:type_name -> base.BaseResponse
	12, // 8: auth.v1.Generate2FARes.secret:type_name -> auth.v1.TwoFactorSecret
	22, // 9: auth.v1.Generate2FARes.base:type_name -> base.BaseResponse
	22, // 10: auth.v1.Enable2FARes.base:type_name -> base.BaseResponse
	22, // 11: auth.v1.Disable2FARes.base:type_name -> base.BaseResponse
	19, // 12: auth.v1.GetCurrencyListRes.currencies:type_name -> auth.v1.CurrencyInfo
	22, // 13: auth.v1.GetCurrencyListRes.base:type_name -> base.BaseResponse
	3,  // 14: auth.v1.AuthService.Login:input_type -> auth.v1.LoginReq
	5,  // 15: auth.v1.AuthService.DemoLogin:input_type -> auth.v1.DemoLoginReq
	6,  // 16: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterReq
	8,  // 17: auth.v1.AuthService.Logout:input_type -> auth.v1.LogoutReq
	10, // 18: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenReq
	13, // 19: auth.v1.AuthService.Generate2FA:input_type -> auth.v1.Generate2FAReq
	15, // 20: auth.v1.AuthService.Enable2FA:input_type -> auth.v1.Enable2FAReq
	17, // 21: auth.v1.AuthService.Disable2FA:input_type -> auth.v1.Disable2FAReq
	0,  // 22: auth.v1.AuthService.UpdatePassword:input_type -> auth.v1.UpdatePasswordReq
	20, // 23: auth.v1.AuthService.GetCurrencyList:input_type -> auth.v1.GetCurrencyListReq
	4,  // 24: auth.v1.AuthService.Login:output_type -> auth.v1.LoginRes
	4,  // 25: auth.v1.AuthService.DemoLogin:output_type -> auth.v1.LoginRes
	7,  // 26: auth.v1.AuthService.Register:output_type -> auth.v1.RegisterRes
	9,  // 27: auth.v1.AuthService.Logout:output_type -> auth.v1.LogoutRes
	11, // 28: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenRes
	14, // 29: auth.v1.AuthService.Generate2FA:output_type -> auth.v1.Generate2FARes
	16, // 30: auth.v1.AuthService.Enable2FA:output_type -> auth.v1.Enable2FARes
	18, // 31: auth.v1.AuthService.Disable2FA:output_type -> auth.v1.Disable2FARes
	1,  // 32: auth.v1.AuthService.UpdatePassword:output_type -> auth.v1.UpdatePasswordRes
	21, // 33: auth.v1.AuthService.GetCurrencyList:output_type -> auth.v1.GetCurrencyListRes
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
