// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package config

import (
	"gaap-api/api/base"
	"gaap-api/internal/model"
)

// themeToProto converts model.Theme to protobuf base.Theme
func themeToProto(t model.Theme) *base.Theme {
	return &base.Theme{
		Id:     t.Id.String(),
		Name:   t.Name,
		IsDark: t.IsDark,
		Colors: &base.ThemeColors{
			Primary: t.Colors.Primary,
			Bg:      t.Colors.Bg,
			Card:    t.Colors.Card,
			Text:    t.Colors.Text,
			Muted:   t.Colors.Muted,
			Border:  t.Colors.Border,
		},
	}
}

// themesToProtos converts slice of model.Theme to slice of protobuf base.Theme
func themesToProtos(themes []model.Theme) []*base.Theme {
	result := make([]*base.Theme, len(themes))
	for i, t := range themes {
		result[i] = themeToProto(t)
	}
	return result
}

// accountTypeConfigToProto converts model.AccountTypeConfig to protobuf base.AccountTypeConfig
func accountTypeConfigToProto(c model.AccountTypeConfig) *base.AccountTypeConfig {
	return &base.AccountTypeConfig{
		Label: c.Label,
		Color: c.Color,
		Bg:    c.Bg,
		Icon:  c.Icon,
	}
}
